[package]
name = "pocket-universe-pack"
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
pocket-universe = { path = "../../worlds/pocket-universe" }
world-pack-server = { path = "../../crates/world-pack-server" }

[dev-dependencies]
world-host = { path = "../../crates/world-host" }
world-pack-catalog = { path = "../../crates/world-pack-catalog" }
world-projection = { path = "../../crates/world-projection" }
