[package]
name = "world-pack-server"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
world-host = { path = "../world-host" }
world-pack-bundle = { path = "../world-pack-bundle" }
world-pack-protocol = { path = "../world-pack-protocol" }
world-persistence = { path = "../world-persistence" }

[dev-dependencies]
world-pack-process = { path = "../world-pack-process" }
world-projection = { path = "../world-projection" }
