[package]
name = "pocket-universe"
version = "0.14.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
world-agent = { path = "../../crates/world-agent" }
world-core = { path = "../../crates/world-core" }
world-host = { path = "../../crates/world-host" }
world-persistence = { path = "../../crates/world-persistence" }
world-projection = { path = "../../crates/world-projection" }


[dev-dependencies]
world-compare = { path = "../../crates/world-compare" }
