[package]
name = "pocket-universe"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
world-core = { path = "../../crates/world-core" }
world-host = { path = "../../crates/world-host" }
world-persistence = { path = "../../crates/world-persistence" }
world-projection = { path = "../../crates/world-projection" }
