//! Everyday things a player types to someone, with what each one means, for
//! measuring how well this System hears. A phrase may name someone else who
//! lives there (`{x}`, or `{x_zh}` / `{x_ja}` for a name they go by in
//! Chinese or Japanese), a place (`{p}`, `{p_zh}` or `{p_ja}`) or something
//! on the calendar (`{f}`); a World fills them in with its own people,
//! places and festivals.

use crate::Intent;

/// Each phrase and what it means.
pub const PHRASES: &[(&str, Intent)] = &[
    // Greetings.
    ("hi", Intent::Greet),
    ("hello there", Intent::Greet),
    ("good morning!", Intent::Greet),
    ("hiya", Intent::Greet),
    ("morning", Intent::Greet),
    ("yo", Intent::Greet),
    ("good evening", Intent::Greet),
    ("hey there", Intent::Greet),
    ("你好", Intent::Greet),
    ("嗨", Intent::Greet),
    ("早上好", Intent::Greet),
    // How they are.
    ("how are you?", Intent::HowAreYou),
    ("how are you doing today", Intent::HowAreYou),
    ("how's life", Intent::HowAreYou),
    ("you alright?", Intent::HowAreYou),
    ("how have you been", Intent::HowAreYou),
    ("what's up", Intent::HowAreYou),
    ("how are things", Intent::HowAreYou),
    ("how do you feel", Intent::HowAreYou),
    ("you doing ok?", Intent::HowAreYou),
    ("hey, how's it going", Intent::HowAreYou),
    ("你好吗", Intent::HowAreYou),
    ("最近怎么样", Intent::HowAreYou),
    ("还好吗", Intent::HowAreYou),
    // Their day.
    ("how was your day", Intent::Day),
    ("what have you been up to", Intent::Day),
    ("what did you do today", Intent::Day),
    ("had a good day?", Intent::Day),
    ("been busy?", Intent::Day),
    ("what are you doing", Intent::Day),
    ("anything fun today?", Intent::Day),
    ("今天过得怎么样", Intent::Day),
    ("你在忙什么", Intent::Day),
    // How someone else is.
    ("how's {x}?", Intent::HowIs),
    ("how is {x} doing", Intent::HowIs),
    ("is {x} ok?", Intent::HowIs),
    ("have you seen {x} lately", Intent::HowIs),
    ("what's {x} up to", Intent::HowIs),
    ("{x_zh}最近怎么样", Intent::HowIs),
    ("{x_zh}还好吗", Intent::HowIs),
    // What they think of someone.
    ("what do you think of {x}", Intent::ThinkOf),
    ("do you like {x}?", Intent::ThinkOf),
    ("how do you feel about {x}", Intent::ThinkOf),
    ("do you and {x} get along?", Intent::ThinkOf),
    ("what's {x} like", Intent::ThinkOf),
    ("tell me about {x}", Intent::ThinkOf),
    ("is {x} nice?", Intent::ThinkOf),
    ("can {x} be trusted", Intent::ThinkOf),
    ("你觉得{x_zh}怎么样", Intent::ThinkOf),
    // A quarrel with someone.
    ("why are you angry at {x}", Intent::Quarrel),
    ("what happened between you and {x}", Intent::Quarrel),
    ("did you fight with {x}?", Intent::Quarrel),
    ("are you mad at {x}?", Intent::Quarrel),
    ("what's your problem with {x}", Intent::Quarrel),
    ("why don't you like {x}", Intent::Quarrel),
    ("你和{x_zh}吵架了吗", Intent::Quarrel),
    ("你为什么生{x_zh}的气", Intent::Quarrel),
    // Advice to make up.
    ("you should make up with {x}", Intent::Reconcile),
    ("you and {x} should talk", Intent::Reconcile),
    ("why not patch things up with {x}", Intent::Reconcile),
    ("go say sorry to {x}", Intent::Reconcile),
    ("forgive {x}", Intent::Reconcile),
    ("life's too short, make peace with {x}", Intent::Reconcile),
    ("你应该和{x_zh}和好", Intent::Reconcile),
    ("去跟{x_zh}道个歉吧", Intent::Reconcile),
    // Their friends.
    ("who's your best friend", Intent::Friends),
    ("who are your friends", Intent::Friends),
    ("who do you like here", Intent::Friends),
    ("who don't you get on with", Intent::Friends),
    ("who do you trust", Intent::Friends),
    ("do you have friends here?", Intent::Friends),
    ("你最好的朋友是谁", Intent::Friends),
    ("你和谁关系好", Intent::Friends),
    // What they think of the player.
    ("what do you think of me", Intent::Standing),
    ("do you like me?", Intent::Standing),
    ("are we friends?", Intent::Standing),
    ("how am i doing", Intent::Standing),
    ("do you trust me", Intent::Standing),
    ("你觉得我怎么样", Intent::Standing),
    ("你喜欢我吗", Intent::Standing),
    // News.
    ("any news?", Intent::News),
    ("what's new", Intent::News),
    ("anything happening?", Intent::News),
    ("heard any gossip", Intent::News),
    ("what's going on around here", Intent::News),
    ("tell me something interesting", Intent::News),
    ("有什么新鲜事", Intent::News),
    ("最近发生了什么", Intent::News),
    // What they need.
    ("do you need anything", Intent::Need),
    ("can i help", Intent::Need),
    ("what can i do for you", Intent::Need),
    ("is there anything you want", Intent::Need),
    ("do you need money", Intent::Need),
    ("how can i help you?", Intent::Need),
    ("你需要什么", Intent::Need),
    ("我能帮你什么", Intent::Need),
    // Their work.
    ("how's work", Intent::Work),
    ("how's business", Intent::Work),
    ("busy at work?", Intent::Work),
    ("what do you do", Intent::Work),
    ("what's your job", Intent::Work),
    ("do you like your job", Intent::Work),
    ("工作怎么样", Intent::Work),
    ("生意好吗", Intent::Work),
    // A place.
    ("how's the {p}", Intent::Place),
    ("what's the {p} like", Intent::Place),
    ("anyone at the {p}?", Intent::Place),
    ("tell me about the {p}", Intent::Place),
    ("{p_zh}怎么样", Intent::Place),
    // Kind words.
    ("you're great", Intent::Compliment),
    ("love the bread", Intent::Compliment),
    ("you look lovely today", Intent::Compliment),
    ("nice hat", Intent::Compliment),
    ("you're doing a great job", Intent::Compliment),
    ("i like you", Intent::Compliment),
    ("you're so kind", Intent::Compliment),
    ("you're the best", Intent::Compliment),
    ("well done", Intent::Compliment),
    ("你真棒", Intent::Compliment),
    ("你好厉害", Intent::Compliment),
    ("你真好", Intent::Compliment),
    // Thanks.
    ("thanks", Intent::Thank),
    ("thank you so much", Intent::Thank),
    ("cheers", Intent::Thank),
    ("much appreciated", Intent::Thank),
    ("thanks for your help", Intent::Thank),
    ("谢谢", Intent::Thank),
    ("多谢你", Intent::Thank),
    // Comfort.
    ("don't worry", Intent::Comfort),
    ("cheer up", Intent::Comfort),
    ("it'll be ok", Intent::Comfort),
    ("i'm here for you", Intent::Comfort),
    ("sorry to hear that", Intent::Comfort),
    ("hang in there", Intent::Comfort),
    ("things will get better", Intent::Comfort),
    ("you're not alone", Intent::Comfort),
    ("别担心", Intent::Comfort),
    ("会好起来的", Intent::Comfort),
    ("加油", Intent::Comfort),
    // Apologies.
    ("sorry", Intent::Apologize),
    ("i'm sorry", Intent::Apologize),
    ("my bad", Intent::Apologize),
    ("i apologise", Intent::Apologize),
    ("forgive me", Intent::Apologize),
    ("i didn't mean it", Intent::Apologize),
    ("sorry about earlier", Intent::Apologize),
    ("对不起", Intent::Apologize),
    ("抱歉", Intent::Apologize),
    // Rudeness.
    ("you're stupid", Intent::Rude),
    ("shut up", Intent::Rude),
    ("you're annoying", Intent::Rude),
    ("go away", Intent::Rude),
    ("i hate you", Intent::Rude),
    ("you're useless", Intent::Rude),
    ("what an idiot", Intent::Rude),
    ("nobody likes you", Intent::Rude),
    ("你真笨", Intent::Rude),
    ("闭嘴", Intent::Rude),
    ("烦死了", Intent::Rude),
    // Goodbyes.
    ("bye", Intent::Farewell),
    ("see you later", Intent::Farewell),
    ("goodbye", Intent::Farewell),
    ("good night", Intent::Farewell),
    ("i have to go", Intent::Farewell),
    ("gotta go", Intent::Farewell),
    ("take care", Intent::Farewell),
    ("再见", Intent::Farewell),
    ("回头见", Intent::Farewell),
    // Worries.
    ("you look tired", Intent::Worry),
    ("are you lonely?", Intent::Worry),
    ("what worries you", Intent::Worry),
    ("are you happy here", Intent::Worry),
    ("is something wrong", Intent::Worry),
    ("what's bothering you", Intent::Worry),
    ("you seem down", Intent::Worry),
    ("are you ok? you seem sad", Intent::Worry),
    ("你看起来很累", Intent::Worry),
    ("你孤单吗", Intent::Worry),
    ("你在担心什么", Intent::Worry),
    // The weather.
    ("nice weather today", Intent::Weather),
    ("is it going to rain", Intent::Weather),
    ("cold today, isn't it", Intent::Weather),
    ("what a storm", Intent::Weather),
    ("lovely sunshine", Intent::Weather),
    ("天气怎么样", Intent::Weather),
    ("今天好冷", Intent::Weather),
    // What is coming up.
    ("what's coming up", Intent::Coming),
    ("anything on this week?", Intent::Coming),
    ("are you going to {f}?", Intent::Coming),
    ("when's the next festival", Intent::Coming),
    ("any plans?", Intent::Coming),
    ("looking forward to {f}?", Intent::Coming),
    ("有什么节日", Intent::Coming),
    ("最近有什么活动", Intent::Coming),
    // Gifts.
    ("i brought you flowers", Intent::Gift),
    ("here, this is for you", Intent::Gift),
    ("i got you a present", Intent::Gift),
    ("have a gift", Intent::Gift),
    ("i made you something", Intent::Gift),
    ("这是送你的", Intent::Gift),
    ("给你带了礼物", Intent::Gift),
    // Invitations.
    ("want to get a drink later", Intent::Invite),
    ("fancy a walk?", Intent::Invite),
    ("let's have lunch", Intent::Invite),
    ("join me for tea", Intent::Invite),
    ("shall we go for a walk", Intent::Invite),
    ("wanna hang out", Intent::Invite),
    ("一起喝一杯吧", Intent::Invite),
    ("我们去散步吧", Intent::Invite),
    // About themselves.
    ("tell me about yourself", Intent::AboutYou),
    ("who are you", Intent::AboutYou),
    ("what's your name", Intent::AboutYou),
    ("what do you like doing", Intent::AboutYou),
    ("what do you do for fun", Intent::AboutYou),
    ("where are you from", Intent::AboutYou),
    ("介绍一下你自己", Intent::AboutYou),
    ("你喜欢做什么", Intent::AboutYou),
    // Family.
    ("do you have family", Intent::Family),
    ("are you married", Intent::Family),
    ("any kids?", Intent::Family),
    ("tell me about your family", Intent::Family),
    ("are you seeing anyone", Intent::Family),
    ("你有家人吗", Intent::Family),
    ("你结婚了吗", Intent::Family),
    // Just keeping the conversation going.
    ("ok", Intent::Ack),
    ("yeah", Intent::Ack),
    ("i see", Intent::Ack),
    ("haha", Intent::Ack),
    ("cool", Intent::Ack),
    ("hmm", Intent::Ack),
    ("sure", Intent::Ack),
    ("好的", Intent::Ack),
    ("嗯", Intent::Ack),
    ("哈哈", Intent::Ack),
    // Found not understood or misheard when first tried, and kept.
    ("good afternoon", Intent::Greet),
    ("hey you", Intent::Greet),
    ("hello again", Intent::Greet),
    ("how you been?", Intent::HowAreYou),
    ("everything ok with you?", Intent::HowAreYou),
    ("how are you feeling today", Intent::HowAreYou),
    ("你今天怎么样", Intent::HowAreYou),
    ("what have you been doing all day", Intent::Day),
    ("did you have a nice day", Intent::Day),
    ("how's your day going", Intent::Day),
    ("how's {x} getting on", Intent::HowIs),
    ("is {x} alright", Intent::HowIs),
    ("{x_zh}怎么样了", Intent::HowIs),
    ("what's your opinion of {x}", Intent::ThinkOf),
    ("are you fond of {x}", Intent::ThinkOf),
    ("do you get on with {x}", Intent::ThinkOf),
    ("did something happen with {x}", Intent::Quarrel),
    ("why are you upset with {x}", Intent::Quarrel),
    ("are you and {x} fighting", Intent::Quarrel),
    ("maybe you should apologise to {x}", Intent::Reconcile),
    ("try to make up with {x}", Intent::Reconcile),
    ("who's your closest friend", Intent::Friends),
    ("who don't you like", Intent::Friends),
    ("do you think i'm doing ok", Intent::Standing),
    ("what do you make of me", Intent::Standing),
    ("are you angry with me", Intent::Standing),
    ("seen anything interesting lately", Intent::News),
    ("what's the latest", Intent::News),
    ("tell me the news", Intent::News),
    ("need a hand?", Intent::Need),
    ("anything you need?", Intent::Need),
    ("can i get you anything", Intent::Need),
    ("how's the work going", Intent::Work),
    ("what do you do for work", Intent::Work),
    ("is work ok", Intent::Work),
    ("the {p} looks busy", Intent::Place),
    ("is the {p} open", Intent::Place),
    ("you're a star", Intent::Compliment),
    ("you're wonderful", Intent::Compliment),
    ("great bread today", Intent::Compliment),
    ("你太好了", Intent::Compliment),
    ("thank you kindly", Intent::Thank),
    ("ta", Intent::Thank),
    ("it's going to be alright", Intent::Comfort),
    ("don't be sad", Intent::Comfort),
    ("you'll get through this", Intent::Comfort),
    ("sorry, my mistake", Intent::Apologize),
    ("i was wrong", Intent::Apologize),
    ("please forgive me", Intent::Apologize),
    ("you're an idiot", Intent::Rude),
    ("leave me alone", Intent::Rude),
    ("you're boring", Intent::Rude),
    ("catch you later", Intent::Farewell),
    ("i'd better be off", Intent::Farewell),
    ("night night", Intent::Farewell),
    ("you seem tired", Intent::Worry),
    ("are you alright? you look upset", Intent::Worry),
    ("anything worrying you", Intent::Worry),
    ("chilly out, isn't it", Intent::Weather),
    ("what a lovely day", Intent::Weather),
    ("looks like rain", Intent::Weather),
    ("what's happening this week", Intent::Coming),
    ("is there a party soon", Intent::Coming),
    ("i got this for you", Intent::Gift),
    ("a little something for you", Intent::Gift),
    ("come for a drink", Intent::Invite),
    ("want to take a walk", Intent::Invite),
    ("let's get dinner", Intent::Invite),
    ("what are you like", Intent::AboutYou),
    ("tell me a bit about you", Intent::AboutYou),
    ("have you got a partner", Intent::Family),
    ("do you have children", Intent::Family),
    ("ah okay", Intent::Ack),
    ("interesting", Intent::Ack),
    ("true", Intent::Ack),
    ("morning, how are we", Intent::HowAreYou),
    ("hey hey", Intent::Greet),
    ("how's everything", Intent::HowAreYou),
    ("you well?", Intent::HowAreYou),
    ("what did you get up to today", Intent::Day),
    ("how's today been", Intent::Day),
    ("how's {x} keeping", Intent::HowIs),
    ("is {x} doing alright these days", Intent::HowIs),
    ("what do you reckon about {x}", Intent::ThinkOf),
    ("is {x} a good sort", Intent::ThinkOf),
    ("you two not talking, you and {x}?", Intent::Quarrel),
    ("what went wrong with {x}", Intent::Quarrel),
    ("you ought to forgive {x}", Intent::Reconcile),
    ("could you two make it up, you and {x}", Intent::Reconcile),
    ("who are you closest to", Intent::Friends),
    ("anyone here you can't stand?", Intent::Friends),
    ("am i welcome here", Intent::Standing),
    ("be honest, what do you think of me", Intent::Standing),
    ("what's the word around town", Intent::News),
    ("heard anything new", Intent::News),
    ("what would help you", Intent::Need),
    ("could you use some help", Intent::Need),
    ("how's trade", Intent::Work),
    ("long day at work?", Intent::Work),
    ("what's going on at the {p}", Intent::Place),
    ("is the {p} busy today", Intent::Place),
    ("you're a treasure", Intent::Compliment),
    ("love your work", Intent::Compliment),
    ("that's very kind of you", Intent::Thank),
    ("thanks a lot", Intent::Thank),
    ("chin up", Intent::Comfort),
    ("it's not your fault", Intent::Comfort),
    ("i'm really sorry", Intent::Apologize),
    ("sorry for what i said", Intent::Apologize),
    ("you're a joke", Intent::Rude),
    ("get out of my face", Intent::Rude),
    ("see ya", Intent::Farewell),
    ("i'll leave you to it", Intent::Farewell),
    ("you look worn out", Intent::Worry),
    ("is anything the matter", Intent::Worry),
    ("you seem lonely", Intent::Worry),
    ("bit windy today", Intent::Weather),
    ("what's the weather doing", Intent::Weather),
    ("what's on this month", Intent::Coming),
    ("any celebrations coming up", Intent::Coming),
    ("got a little present for you", Intent::Gift),
    ("these are for you", Intent::Gift),
    ("fancy a pint", Intent::Invite),
    ("come and eat with me", Intent::Invite),
    ("tell me something about yourself", Intent::AboutYou),
    ("what's your story", Intent::AboutYou),
    ("got any family here", Intent::Family),
    ("is there someone special", Intent::Family),
    ("right, ok", Intent::Ack),
    ("fair enough", Intent::Ack),
    ("oh really", Intent::Ack),
    ("你今天好吗", Intent::HowAreYou),
    ("{x_zh}最近好吗", Intent::HowIs),
    ("给你的", Intent::Gift),
    ("我走了", Intent::Farewell),
    ("evening all", Intent::Greet),
    ("how goes it", Intent::HowAreYou),
    ("you keeping alright?", Intent::HowAreYou),
    ("what's been going on with you today", Intent::Day),
    ("anything exciting happen today", Intent::Day),
    ("{x} been ok?", Intent::HowIs),
    ("how's {x} holding up", Intent::HowIs),
    ("what sort of person is {x}", Intent::ThinkOf),
    ("you rate {x}?", Intent::ThinkOf),
    ("is there bad blood between you and {x}", Intent::Quarrel),
    ("why is {x} avoiding you", Intent::Quarrel),
    ("bury the hatchet with {x}", Intent::Reconcile),
    ("who would you call a friend here", Intent::Friends),
    ("who gets on your nerves", Intent::Friends),
    ("do i have your trust", Intent::Standing),
    ("are you glad i'm here", Intent::Standing),
    ("anything going on", Intent::News),
    ("any word from the others", Intent::News),
    ("is there something i could do", Intent::Need),
    ("what are you short of", Intent::Need),
    ("work treating you ok?", Intent::Work),
    ("how's the job", Intent::Work),
    ("who's at the {p}", Intent::Place),
    ("what do you think of the {p}", Intent::Place),
    ("you've done brilliantly", Intent::Compliment),
    ("what a lovely smile", Intent::Compliment),
    ("thanks ever so much", Intent::Thank),
    ("i owe you one", Intent::Thank),
    ("there there", Intent::Comfort),
    ("you're doing your best", Intent::Comfort),
    ("forgive me please", Intent::Apologize),
    ("i'm so sorry about that", Intent::Apologize),
    ("drop dead", Intent::Rude),
    ("you disgust me", Intent::Rude),
    ("see you around", Intent::Farewell),
    ("off i go then", Intent::Farewell),
    ("are you getting enough sleep", Intent::Worry),
    ("you don't look well", Intent::Worry),
    ("brr it's freezing", Intent::Weather),
    ("think it'll clear up?", Intent::Weather),
    ("anything special coming", Intent::Coming),
    ("what's the next big event", Intent::Coming),
    ("brought something for you", Intent::Gift),
    ("a gift, for you", Intent::Gift),
    ("coffee sometime?", Intent::Invite),
    ("care to join me for supper", Intent::Invite),
    ("what makes you tick", Intent::AboutYou),
    ("where did you grow up", Intent::AboutYou),
    ("anyone waiting for you at home", Intent::Family),
    ("how's the wife", Intent::Family),
    ("alright then", Intent::Ack),
    ("mm", Intent::Ack),
    ("你最近在做什么", Intent::Day),
    ("你喜欢{x_zh}吗", Intent::ThinkOf),
    ("下雨了", Intent::Weather),
    ("我请你喝咖啡", Intent::Invite),
    // In Japanese, as a player would type it: polite or casual.
    ("こんにちは", Intent::Greet),
    ("おはよう！", Intent::Greet),
    ("こんばんは", Intent::Greet),
    ("やあ", Intent::Greet),
    ("おはようございます", Intent::Greet),
    ("元気？", Intent::HowAreYou),
    ("調子はどう？", Intent::HowAreYou),
    ("お元気ですか", Intent::HowAreYou),
    ("最近どう？", Intent::HowAreYou),
    ("元気にしてた？", Intent::HowAreYou),
    ("今日はどうだった？", Intent::Day),
    ("今日は何してたの？", Intent::Day),
    ("今何してるの？", Intent::Day),
    ("忙しかった？", Intent::Day),
    ("{x_ja}は元気？", Intent::HowIs),
    ("{x_ja}はどうしてる？", Intent::HowIs),
    ("最近{x_ja}に会った？", Intent::HowIs),
    ("{x_ja}のことどう思う？", Intent::ThinkOf),
    ("{x_ja}ってどんな人？", Intent::ThinkOf),
    ("{x_ja}のこと好き？", Intent::ThinkOf),
    ("{x_ja}とけんかしたの？", Intent::Quarrel),
    ("なんで{x_ja}に怒ってるの？", Intent::Quarrel),
    ("{x_ja}と何かあった？", Intent::Quarrel),
    ("{x_ja}と仲直りしなよ", Intent::Reconcile),
    ("{x_ja}に謝ったら？", Intent::Reconcile),
    ("{x_ja}と話し合ったほうがいいよ", Intent::Reconcile),
    ("親友は誰？", Intent::Friends),
    ("仲のいい人は誰？", Intent::Friends),
    ("ここに友だちはいる？", Intent::Friends),
    ("私のことどう思う？", Intent::Standing),
    ("私のこと好き？", Intent::Standing),
    ("私たち友だちだよね？", Intent::Standing),
    ("私のこと信頼してる？", Intent::Standing),
    ("何か新しいことあった？", Intent::News),
    ("最近何かあった？", Intent::News),
    ("何か噂ある？", Intent::News),
    ("何か必要なものある？", Intent::Need),
    ("何か手伝おうか？", Intent::Need),
    ("何かできることある？", Intent::Need),
    ("仕事はどう？", Intent::Work),
    ("商売はどう？", Intent::Work),
    ("仕事は忙しい？", Intent::Work),
    ("{p_ja}はどう？", Intent::Place),
    ("{p_ja}の様子は？", Intent::Place),
    ("すごいね", Intent::Compliment),
    ("あなたは最高だね", Intent::Compliment),
    ("パンがおいしいね", Intent::Compliment),
    ("よくやったね", Intent::Compliment),
    ("優しいね", Intent::Compliment),
    ("ありがとう", Intent::Thank),
    ("どうもありがとう", Intent::Thank),
    ("助かったよ", Intent::Thank),
    ("本当に感謝してる", Intent::Thank),
    ("心配しないで", Intent::Comfort),
    ("元気出して", Intent::Comfort),
    ("きっと大丈夫だよ", Intent::Comfort),
    ("がんばって", Intent::Comfort),
    ("ひとりじゃないよ", Intent::Comfort),
    ("ごめん", Intent::Apologize),
    ("ごめんなさい", Intent::Apologize),
    ("すみませんでした", Intent::Apologize),
    ("申し訳ない", Intent::Apologize),
    ("さっきは悪かった", Intent::Apologize),
    ("ばかじゃないの", Intent::Rude),
    ("うるさい", Intent::Rude),
    ("黙れ", Intent::Rude),
    ("あっち行って", Intent::Rude),
    ("大嫌い", Intent::Rude),
    ("役立たず", Intent::Rude),
    ("さようなら", Intent::Farewell),
    ("またね", Intent::Farewell),
    ("じゃあね", Intent::Farewell),
    ("おやすみ", Intent::Farewell),
    ("もう行かなきゃ", Intent::Farewell),
    ("疲れてるみたいだね", Intent::Worry),
    ("さびしいの？", Intent::Worry),
    ("何か心配ごと？", Intent::Worry),
    ("大丈夫？悲しそうだね", Intent::Worry),
    ("元気ないね", Intent::Worry),
    ("いい天気だね", Intent::Weather),
    ("雨が降りそう", Intent::Weather),
    ("今日は寒いね", Intent::Weather),
    ("天気はどう？", Intent::Weather),
    ("次のお祭りはいつ？", Intent::Coming),
    ("何か予定ある？", Intent::Coming),
    ("今週は何かある？", Intent::Coming),
    ("これあげる", Intent::Gift),
    ("プレゼントを持ってきたよ", Intent::Gift),
    ("花を持ってきたよ", Intent::Gift),
    ("あなたにと思って", Intent::Gift),
    ("一緒に散歩しない？", Intent::Invite),
    ("一杯飲みに行こう", Intent::Invite),
    ("お茶しない？", Intent::Invite),
    ("ご飯行こうよ", Intent::Invite),
    ("あなたのことを教えて", Intent::AboutYou),
    ("趣味は何？", Intent::AboutYou),
    ("出身はどこ？", Intent::AboutYou),
    ("名前は？", Intent::AboutYou),
    ("家族はいる？", Intent::Family),
    ("結婚してるの？", Intent::Family),
    ("子どもはいる？", Intent::Family),
    ("うん", Intent::Ack),
    ("そっか", Intent::Ack),
    ("なるほど", Intent::Ack),
    ("へえ", Intent::Ack),
    ("わかった", Intent::Ack),
    // Nothing anyone could make sense of.
    ("purple elephants", Intent::Unclear),
    ("asdf", Intent::Unclear),
    ("the moon is made of cheese", Intent::Unclear),
];

/// What a World fills a phrase's blanks with.
#[derive(Clone, Debug, Default)]
pub struct Blanks {
    /// Someone else who lives there, by the name they are called.
    pub person: String,
    /// A name they go by in Chinese, if they have one.
    pub person_zh: Option<String>,
    /// A place, as it is usually called ("bakery").
    pub place: String,
    pub place_zh: Option<String>,
    /// A name they go by in Japanese, if they have one.
    pub person_ja: Option<String>,
    pub place_ja: Option<String>,
    /// Something on the calendar, by name.
    pub occasion: Option<String>,
}

/// The phrases with a World's blanks filled in, leaving out any whose
/// blank the World has nothing for.
pub fn filled(blanks: &Blanks) -> Vec<(String, Intent)> {
    PHRASES
        .iter()
        .filter_map(|(phrase, intent)| {
            let mut text = phrase.to_string();
            for (blank, value) in [
                ("{x_zh}", blanks.person_zh.as_deref()),
                ("{x_ja}", blanks.person_ja.as_deref()),
                ("{x}", Some(blanks.person.as_str())),
                ("{p_zh}", blanks.place_zh.as_deref()),
                ("{p_ja}", blanks.place_ja.as_deref()),
                ("{p}", Some(blanks.place.as_str())),
                ("{f}", blanks.occasion.as_deref()),
            ] {
                if text.contains(blank) {
                    text = text.replace(blank, value?);
                }
            }
            Some((text, *intent))
        })
        .collect()
}

/// How a World heard the corpus.
#[derive(Clone, Debug, Default)]
pub struct Score {
    pub phrases: usize,
    /// Phrases heard as nothing, though they meant something.
    pub unclear: Vec<String>,
    /// Phrases heard as something they did not mean: what was said, what
    /// it meant and what it was heard as.
    pub misheard: Vec<(String, Intent, Intent)>,
}

impl Score {
    /// The share of phrases heard as nothing, in percent.
    pub fn unclear_percent(&self) -> f64 {
        100.0 * self.unclear.len() as f64 / self.phrases.max(1) as f64
    }
}

/// Hears every phrase with `hear` and scores it.
pub fn score(phrases: &[(String, Intent)], mut hear: impl FnMut(&str) -> Intent) -> Score {
    let mut score = Score {
        phrases: phrases.len(),
        ..Score::default()
    };
    for (phrase, meant) in phrases {
        let heard = hear(phrase);
        if heard == *meant {
            continue;
        }
        if heard == Intent::Unclear {
            score.unclear.push(phrase.clone());
        } else {
            score.misheard.push((phrase.clone(), *meant, heard));
        }
    }
    score
}
