[package]
name = "world-builtins"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
world-host = { path = "../world-host" }
world-i18n = { path = "../world-i18n" }
tiny-society = { path = "../../worlds/tiny-society" }
future-archaeologist = { path = "../../worlds/future-archaeologist" }

[dev-dependencies]
world-projection = { path = "../world-projection" }
