[package]
name = "world-pack-process"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
world-host = { path = "../world-host" }
world-pack-protocol = { path = "../world-pack-protocol" }
world-persistence = { path = "../world-persistence" }
world-projection = { path = "../world-projection" }

[dev-dependencies]
serde_json = "1"
