[package]
name = "world-cli"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
serde_json = "1"
world-builtins = { path = "../world-builtins" }
world-query = { path = "../world-query" }
world-integrity = { path = "../world-integrity" }
world-persistence = { path = "../world-persistence" }
world-projection = { path = "../world-projection" }
