[package]
name = "world-strategy"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
world-compare = { path = "../world-compare" }
world-host = { path = "../world-host" }
world-persistence = { path = "../world-persistence" }
world-projection = { path = "../world-projection" }

[dev-dependencies]
tiny-society = { path = "../../worlds/tiny-society" }
