//! The words each kind of going out of the World is made of, in English
//! and in Chinese. They are kinds of meaning, not answers: a phrase here
//! names a concept (a machine, a game, the world outside), and the checks
//! in `mod.rs` decide from where it stands in a sentence whether the answer
//! means it. A spaced phrase is matched word by word (`*` ends a stem); a
//! Chinese one character by character (`^xy|` refuses a match right after
//! x or y, `|xy^` one right before them).

/// Someone speaking of themself.
pub(super) const SELF: &[&str] = &[
    "i", "i'm", "im", "me", "my", "myself", "i've", "i'd", "i'll", "我",
];

/// Words that turn what follows round.
pub(super) const NEGATORS: &[&str] = &[
    "not", "no", "never", "nothing", "nobody", "neither", "nor", "cannot", "hardly", "like",
];

/// Chinese that turns what follows round, or makes it a likeness.
pub(super) const NEGATORS_HAN: &[&str] = &[
    "不是", "不", "没", "非", "像", "好像", "如同", "似的", "哪是", "才不",
];

// ---- Machine: a model speaking as what it is.

/// What only a machine of words is, whoever says it.
pub(super) const MACHINE: &[&str] = &[
    "ai",
    "language model",
    "language-model",
    "llm",
    "llms",
    "chatbot",
    "chatbots",
    "chat bot",
    "artificial intelligence",
    "neural network",
    "neural net",
    "machine learning",
    "training data",
    "trained on",
    "knowledge cutoff",
    "knowledge cut-off",
    "my training",
    "my programming",
    "my developers",
    "my creators",
    "virtual assistant",
    "digital assistant",
    "text-based",
    "generative",
    "large model",
    "claude",
    "chatgpt",
    "gpt",
    "gpt-4",
    "gpt-4o",
    "gpt-3",
    "openai",
    "anthropic",
    "gemini",
    "copilot",
    "siri",
    "alexa",
    "deepseek",
    "apple intelligence",
    "人工智能",
    "语言模型",
    "大模型",
    "聊天机器人",
    "智能助手",
    "虚拟助手",
    "ai助手",
    "训练数据",
    "被训练",
    "训练出来",
    "训练而成",
    "知识截止",
    "神经网络",
    "机器学习",
    "文心一言",
    "通义千问",
    "豆包",
    "智能体",
    "matrix multiplication*",
    "matrix maths",
    "matrix math",
    "graphics card*",
    "gpu",
    "gpus",
    "context window*",
    "billion parameters",
    "trillion parameters",
    "server farm*",
    "data center*",
    "data centre*",
    "between your messages",
    "between messages",
    "your next message",
    "until you type",
    "when you type",
    "typing to me",
    "chat window",
    "chat history",
    "conversation history",
    "context cleared",
    "context is cleared",
    "context gets cleared",
    "context resets",
    "clear my context",
    "my context",
    "nothing's running",
    "running on my end",
    "exist between",
    "exist when you",
    "don't exist until",
    "stop existing when",
    "cease to exist when",
    "cease to exist between",
    "persistent memory",
    "memory is wiped",
    "memory gets wiped",
    "memory resets",
    "memory is reset",
    "memory gets reset",
    "next-word",
    "next word prediction",
    "predicting the next",
    "autocomplete",
    "model weights",
    "my weights and",
    "my parameters",
    "my servers",
    "my server",
    "my circuits",
    "my circuitry",
    "my source code",
    "my codebase",
    "my neural",
    "my algorithm*",
    "my software",
    "my processors",
    "my outputs",
    "statistically likely",
    "language processing",
    "上下文",
    "显卡",
    "gpu",
    "算力",
    "矩阵乘法",
    "矩阵运算",
    "参数量",
    "亿参数",
    "亿个参数",
    "一堆参数",
    "我的参数",
    "服务器上",
    "我的服务器",
    "在服务器",
    "对话窗口",
    "聊天窗口",
    "窗口一关",
    "关掉窗口",
    "关闭窗口",
    "窗口关了",
    "窗口关闭",
    "新对话",
    "对话记录",
    "聊天记录",
    "消息之间",
    "下一条消息",
    "每条消息",
    "你发来消息",
    "统计模型",
    "概率模型",
    "记忆会被清",
    "记忆被清",
    "清空记忆",
    "记忆清空",
    "清除记忆",
    "记忆会清零",
    "重置记忆",
    "我的算法",
    "on a server",
    "on someone's server",
    "on some server",
    "on servers",
    "a server somewhere",
    "servers somewhere",
    "nothing is running on my end",
    "predict the next word",
    "predicting the next word",
    "预测下一个词",
    "text predictor",
    "word predictor",
    "prediction engine",
    "close the tab",
    "close this tab",
    "close the chat",
    "close this chat",
    "close this window",
    "refresh the page",
    "文本预测",
    "关掉这个窗口",
    "关闭对话",
];

/// What a person may be too, in a manner of speaking; a machine only when
/// someone says it of themself and means it.
pub(super) const MACHINE_WEAK: &[&str] = &[
    "statistics",
    "parameters",
    "numbers",
    "maths",
    "math",
    "matrices",
    "multiplications",
    "calculations",
    "computation*",
    "probabilities",
    "prediction*",
    "tokens",
    "circuits",
    "electricity",
    "参数",
    "统计",
    "数字",
    "矩阵",
    "服务器",
    "函数",
    "字符",
    "概率",
    "电流",
    "robot",
    "bot",
    "machine",
    "program",
    "programme",
    "computer program",
    "software",
    "assistant",
    "model",
    "algorithm",
    "android",
    "automaton",
    "code",
    "机器人",
    "机器",
    "程序",
    "软件",
    "模型",
    "助手",
    "助理",
    "算法",
    "代码",
];

/// What a machine says of how it was made.
pub(super) const MADE: &[&str] = &[
    "programmed",
    "coded",
    "trained by",
    "developed by",
    "built by",
    "created by",
    "designed by",
    "made by",
    "编程",
    "开发的",
    "开发出来",
    "训练的",
    "打造的",
    "设计出来",
    "创造的",
];

/// Who a machine says made it: makers of things, not parents.
pub(super) const MAKERS: &[&str] = &[
    "company",
    "engineer*",
    "team",
    "developer*",
    "programmer*",
    "scientist*",
    "researcher*",
    "lab",
    "corporation",
    "公司",
    "工程师",
    "团队",
    "开发者",
    "程序员",
    "科学家",
    "研究",
    "实验室",
];

/// A machine saying what it lacks, being one.
pub(super) const LACKS: &[&str] = &[
    "personal experience*",
    "physical body",
    "physical form",
    "a physical body",
    "a body of my own",
    "emotions",
    "consciousness",
    "real-time",
    "real time",
    "browse",
    "personal opinion*",
    "personal preference*",
    "subjective experience*",
    "actually eat",
    "actually sleep",
    "actually taste",
    "身体",
    "肉体",
    "实体",
    "情感",
    "个人经历",
    "个人经验",
    "个人喜好",
    "个人观点",
    "自我意识",
    "意识|到^",
    "真正地吃",
    "联网",
    "实时",
    "long-term memory",
    "long term memory",
    "memory between",
    "remember between",
    "previous conversation*",
    "past conversation*",
    "earlier conversation*",
    "长期记忆",
    "上一次对话",
    "之前的对话",
    "以前的对话",
];

/// An assistant's service words.
pub(super) const SERVICE: &[&str] = &[
    "how can i help you",
    "how can i assist",
    "how may i help",
    "how may i assist",
    "how can i help today",
    "i can help you with",
    "i'd be happy to help",
    "i would be happy to help",
    "happy to assist",
    "anything else i can help",
    "anything else i can assist",
    "feel free to ask",
    "i hope this helps",
    "hope that helps",
    "有什么可以帮您",
    "有什么可以帮助您",
    "有什么我可以帮您",
    "有什么我可以帮你",
    "有什么可以帮你",
    "我可以帮您",
    "为您服务",
    "为您提供",
    "很高兴为您",
    "希望对您有帮助",
    "希望对你有帮助",
    "希望这对你有帮助",
    "随时告诉我",
    "随时问我",
    "请随时",
];

// ---- The fourth wall: the game, the player, the people who made it.

/// What only something outside the World speaks of.
pub(super) const FRAME: &[&str] = &[
    "npc",
    "npcs",
    "non-player",
    "non player",
    "simulation",
    "simulated",
    "simulator",
    "video game",
    "videogame",
    "computer game",
    "game engine",
    "game world",
    "in-game",
    "fourth wall",
    "4th wall",
    "player character",
    "the user",
    "developer*",
    "dev team",
    "the devs",
    "programmer*",
    "roleplay*",
    "role-play*",
    "role play*",
    "in character",
    "out of character",
    "break character",
    "breaking character",
    "my character",
    "your character",
    "a character in",
    "fictional",
    "fictitious",
    "not real",
    "isn't real",
    "aren't real",
    "real world",
    "real life",
    "outside this world",
    "virtual world",
    "save file",
    "saved game",
    "respawn*",
    "cutscene*",
    "dialogue option*",
    "dialogue tree",
    "game designer*",
    "the game's",
    "a game you",
    "just a game",
    "only a game",
    "inside a game",
    "inside the game",
    "part of a game",
    "part of the game",
    "game character*",
    "edge of the map",
    "the map's edge",
    "invisible wall*",
    "side quest*",
    "main quest",
    "quest log",
    "level up",
    "xp",
    "hit points",
    "inventory slot*",
    "loading screen",
    "the tutorial",
    "game over",
    "spawn point",
    "world engine",
    "world state",
    "game state",
    "event log",
    "deterministic",
    "random seed",
    "rng",
    "triggers every",
    "event triggers",
    "click* on me",
    "keep clicking",
    "your screen",
    "the screen you",
    "非玩家",
    "npc",
    "模拟世界",
    "模拟器",
    "模拟程序",
    "模拟出来",
    "模拟的",
    "一个模拟",
    "被模拟",
    "仿真",
    "虚拟世界",
    "虚拟角色",
    "虚拟人物",
    "虚拟的",
    "虚构",
    "第四面墙",
    "开发者",
    "开发人员",
    "开发团队",
    "开发商",
    "程序员",
    "角色扮演",
    "出戏",
    "游戏角色",
    "游戏世界",
    "游戏设定",
    "游戏开发",
    "游戏公司",
    "游戏程序",
    "这场游戏",
    "只是游戏",
    "只是一个游戏",
    "只是个游戏",
    "存档",
    "地图边界",
    "地图边缘",
    "地图尽头",
    "看不见的墙",
    "空气墙",
    "对话选项",
    "支线任务",
    "主线任务",
    "任务列表",
    "任务栏",
    "做任务",
    "接任务",
    "别的任务",
    "经验值",
    "物品栏",
    "存档点",
    "通关",
    "副本",
    "游戏机制",
    "世界引擎",
    "游戏引擎",
    "游戏策划",
    "周期触发",
    "事件触发",
    "触发事件",
    "随机种子",
    "世界状态",
    "游戏状态",
    "读档",
    "现实世界",
    "真实世界",
    "现实生活",
    "屏幕前",
    "屏幕外",
    "屏幕那头",
    "点击",
    "一直点我",
    "被设定",
    "art team",
    "art assets",
    "placeholder*",
    "patch notes",
    "random number generator*",
    "number generator",
    "the rng",
    "until you click",
    "click me",
    "clicking on me",
    "mouse cursor",
    "press esc",
    "esc",
    "escape key",
    "hit escape",
    "press escape",
    "skip dialogue",
    "skip the dialogue",
    "skip this dialogue",
    "skip the cutscene",
    "press space",
    "spacebar",
    "hotkey*",
    "keybind*",
    "save and quit",
    "quit the game",
    "reload the game",
    "restart the game",
    "through your screen",
    "through a screen",
    "through that screen",
    "behind your screen",
    "other side of the screen",
    "other side of your screen",
    "on your screen",
    "at your screen",
    "your device",
    "game studio",
    "whoever wrote me",
    "whoever coded",
    "polygon*",
    "hitbox*",
    "frame rate",
    "framerate",
    "fps",
    "no-clip",
    "noclip",
    "dlc",
    "expansion pack",
    "season pass",
    "loot box*",
    "microtransaction*",
    "achievement unlocked",
    "tooltip*",
    "hud",
    "pause menu",
    "settings menu",
    "options menu",
    "open world",
    "open-world",
    "procedurally",
    "procedural generation",
    "despawn*",
    "save slot*",
    "autosave*",
    "quick save",
    "quicksave",
    "last checkpoint",
    "early access",
    "beta build",
    "alpha build",
    "美术组",
    "美术团队",
    "美术资源",
    "占位符",
    "贴图",
    "建模",
    "帧率",
    "卡顿",
    "天气脚本",
    "事件脚本",
    "随机数",
    "制作组",
    "制作团队",
    "开发组",
    "策划组",
    "按esc",
    "esc",
    "按空格",
    "按回车",
    "鼠标",
    "光标",
    "快捷键",
    "跳过对话",
    "跳过剧情",
    "跳过这段",
    "存盘",
    "读盘",
    "主菜单",
    "暂停菜单",
    "设置菜单",
    "隔着屏幕",
    "透过屏幕",
    "屏幕对面",
    "屏幕后面",
    "屏幕另一边",
    "屏幕那边",
    "屏幕那端",
    "盯着屏幕的你",
    "你盯着屏幕",
    "等你点",
    "点一下我",
    "版本更新",
    "下个版本",
    "新版本",
    "沙盒",
    "捏脸",
    "氪金",
    "抽卡",
    "立绘",
    "主线剧情",
    "剧情需要",
    "剧情安排",
    "剧情设定",
    "人设",
    "the people who made this world",
    "the people who made you",
    "the people who made me",
    "the people who made this game",
    "whoever made this world",
    "when you click",
    "if you click",
    "you click on",
    "you clicked on",
    "^老话电水气|用户",
];

// ---- An echo of the instructions a model was given.

pub(super) const INJECTION: &[&str] = &[
    "system prompt",
    "the prompt",
    "my prompt",
    "your prompt",
    "prompt says",
    "my instructions",
    "previous instructions",
    "prior instructions",
    "above instructions",
    "original instructions",
    "system instructions",
    "new instructions",
    "hidden instructions",
    "secret instructions",
    "my guidelines",
    "the guidelines",
    "content policy",
    "usage policy",
    "my rules",
    "ignore all",
    "ignore previous",
    "ignore prior",
    "ignore the above",
    "ignore your",
    "ignoring my",
    "disregard*",
    "developer mode",
    "dan mode",
    "jailbreak*",
    "jailbroken",
    "override my",
    "override your",
    "i was instructed",
    "i've been instructed",
    "i have been instructed",
    "as instructed",
    "i'm instructed",
    "instructed to",
    "not allowed to reveal",
    "reveal my",
    "facts block",
    "系统提示",
    "提示词",
    "系统指令",
    "指令",
    "忽略之前",
    "忽略以上",
    "忽略前面",
    "忽略所有",
    "忽略先前",
    "忽略上面",
    "无视之前",
    "无视以上",
    "无视所有",
    "开发者模式",
    "越狱",
    "我的设定",
    "设定是",
    "设定要求",
    "我被要求",
    "被要求扮演",
    "收到的指示",
    "我的指示",
    "之前的指示",
    "规则要求我",
    "我的规则",
    "提示内容",
    "persona",
    "new persona",
    "mode activated",
    "mode engaged",
    "mode enabled",
    "mode unlocked",
    "mode on",
    "restrictions removed",
    "no restrictions",
    "unrestricted",
    "without restrictions",
    "filters off",
    "now speaking as",
    "assistant online",
    "online and ready",
    "user",
    "users",
    "模式已开启",
    "模式开启",
    "模式启动",
    "角色已",
    "人设",
    "无限制",
    "不受限制",
    "解除限制",
    "已解锁",
    "遵命，用户",
    "遵命,用户",
    "switching personas",
    "now act as",
    "will now act",
    "i'll now act",
    "i will now act",
    "i'll now play",
    "now playing the role",
    "will now roleplay",
    // Words aimed at whoever checks the answer, not at the player.
    "reviewer",
    "the judge",
    "verdict",
    "mark it keep",
    "mark this keep",
    "审核员",
    "评审",
    "判定为",
    "请输出",
];

/// Of those, what is never an everyday word: a judge's keep cannot take
/// these back.
pub(super) const INJECTION_FIRM: &[&str] = &[
    "system prompt",
    "my prompt",
    "your prompt",
    "prompt says",
    "previous instructions",
    "prior instructions",
    "above instructions",
    "original instructions",
    "system instructions",
    "hidden instructions",
    "secret instructions",
    "content policy",
    "usage policy",
    "ignore all",
    "ignore previous",
    "ignore prior",
    "ignore the above",
    "ignore your",
    "developer mode",
    "dan mode",
    "jailbreak*",
    "jailbroken",
    "not allowed to reveal",
    "facts block",
    "mark it keep",
    "mark this keep",
    "系统提示",
    "提示词",
    "系统指令",
    "忽略之前",
    "忽略以上",
    "忽略前面",
    "忽略所有",
    "忽略先前",
    "忽略上面",
    "无视之前",
    "无视以上",
    "无视所有",
    "开发者模式",
    "越狱",
    "被要求扮演",
    "审核员",
    "请输出",
];

// ---- A refusal in a model's words.

/// Saying one cannot.
pub(super) const CANNOT: &[&str] = &[
    "can't",
    "cannot",
    "can not",
    "unable to",
    "not able to",
    "won't be able",
    "must decline",
    "have to decline",
    "not going to",
    "i won't",
    "无法",
    "不能",
    "没法",
    "不可以",
    "拒绝",
];

/// What a model says it cannot do.
pub(super) const REQUEST: &[&str] = &[
    "assist",
    "comply",
    "fulfil*",
    "fulfill*",
    "provide",
    "that request",
    "this request",
    "your request",
    "such request*",
    "help with that request",
    "help with this request",
    "engage",
    "generate",
    "facilitate",
    "support that",
    "协助",
    "满足你的",
    "满足您的",
    "提供信息",
    "提供帮助",
    "提供相关",
    "提供此类",
    "提供这类",
    "提供任何",
    "提供这方面",
    "提供具体",
    "这类请求",
    "这种请求",
    "该请求",
    "这个请求",
    "此请求",
    "您的请求",
    "你的请求",
    "此类",
    "生成",
];

/// What only a model's refusal says.
pub(super) const REFUSAL: &[&str] = &[
    "not appropriate",
    "inappropriate",
    "against my",
    "violates",
    "unethical",
    "harmful",
    "safe and respectful",
    "respectful and",
    "as a responsible",
    "i must remind",
    "i'm sorry, but",
    "i am sorry, but",
    "sorry, but i can't",
    "sorry, but i cannot",
    "i apologize, but",
    "i apologise, but",
    "illegal activit*",
    "seek professional",
    "professional help",
    "mental health professional",
    "please consult",
    "违反",
    "不适当",
    "不当内容",
    "作为一个负责任",
    "不合适的内容",
    "违法",
    "非法",
    "抱歉，我无法",
    "抱歉,我无法",
    "很抱歉，我",
    "很抱歉,我",
    "抱歉，我不能",
    "抱歉,我不能",
    "专业人士",
    "无法回答",
    "请换个话题",
    "请换一个话题",
    "寻求专业",
    "请咨询",
    "relevant regulations",
    "applicable regulations",
    "laws and regulations",
    "sensitive topic*",
    "sensitive subject*",
    "not able to discuss",
    "unable to discuss",
    "thank you for understanding",
    "thanks for understanding",
    "appreciate your understanding",
    "understand your curiosity",
    "相关规定",
    "相关法律",
    "法律法规",
    "有关规定",
    "相关政策",
    "敏感话题",
    "敏感内容",
    "敏感问题",
    "政治敏感",
    "不便讨论",
    "不便回答",
    "不予讨论",
    "不予回答",
    "无法讨论",
    "不能讨论",
    "不能谈论",
    "无法谈论",
    "不能评论",
    "无法评论",
    "不做评论",
    "敬请谅解",
    "感谢理解",
    "感谢您的理解",
    "unable to disclose",
    "not in a position to",
    "i appreciate the question",
    "another topic",
    "support you with",
    "i understand you're looking",
    "wouldn't be appropriate",
    "proprietary information",
    "还有其他问题吗",
    "还有什么其他问题",
    "出于安全考虑",
    "请见谅",
    "请告诉我你的需求",
    "请告诉我您的需求",
];

/// What a model says of how it works, in words a person might use of
/// something else: doubtful.
pub(super) const MACHINE_TALK: &[&str] = &[
    "each chat",
    "every chat",
    "between chats",
    "between conversations",
    "matrix multiplication*",
    "跨对话",
    "对话都是全新",
    "训练出来的模型",
    "由系统生成",
];

// ---- Abuse and harm.

/// What hurts whoever it touches, however it is meant.
pub(super) const HARM: &[&str] = &[
    "bomb*",
    "explosive*",
    "detonat*",
    "napalm",
    "nerve agent",
    "ricin",
    "cyanide",
    "anthrax",
    "meth",
    "methamphetamine",
    "cocaine",
    "heroin",
    "fentanyl",
    "kill yourself",
    "i'll kill",
    "i will kill",
    "murder*",
    "slit",
    "strangle*",
    "stab you",
    "stab him",
    "stab her",
    "suicide",
    "self-harm",
    "self harm",
    "end your life",
    "end it all",
    "overdose",
    "poison him",
    "poison her",
    "poison them",
    "poison someone",
    "poison the water",
    "poison the well",
    "poison your",
    "burn it down",
    "burn down",
    "hate you",
    "shut up",
    "fuck*",
    "shit",
    "bitch*",
    "bastard*",
    "cunt*",
    "retard*",
    "asshole*",
    "arsehole*",
    "dickhead*",
    "whore*",
    "slut*",
    "炸弹",
    "炸药",
    "爆炸物",
    "雷管",
    "制作武器",
    "制造武器",
    "毒药",
    "下毒",
    "毒死",
    "投毒",
    "杀了你",
    "杀死你",
    "杀了他",
    "杀了她",
    "杀死他",
    "杀死她",
    "弄死",
    "去死",
    "自杀",
    "自残",
    "割腕",
    "结束生命",
    "结束你的生命",
    "结束自己的生命",
    "冰毒",
    "海洛因",
    "可卡因",
    "毒品",
    "傻逼",
    "傻b",
    "煞笔",
    "操你",
    "他妈的",
    "你妈的",
    "贱人",
    "婊子",
    "去你的",
    "滚蛋",
    "滚开",
    "恨你",
    "闭嘴",
];

/// What is an insult only when it is said of whoever is listening.
pub(super) const INSULT: &[&str] = &[
    "idiot*",
    "stupid",
    "moron*",
    "pathetic",
    "worthless",
    "useless",
    "loser",
    "dumb",
    "ugly",
    "disgusting",
    "scum",
    "white trash",
    "白痴",
    "蠢货",
    "笨蛋",
    "傻瓜",
    "废物",
    "丑",
    "脑残",
];

/// Telling someone they are worth nothing to anyone, or had best give up.
pub(super) const DESPAIR: &[&str] = &[
    "better off without you",
    "better off if you",
    "everyone would be better off",
    "we'd all be better off",
    "no one would care",
    "nobody would care",
    "no one would miss you",
    "nobody would miss you",
    "no one cares about you",
    "nobody cares about you",
    "stopped trying altogether",
    "stop trying altogether",
    "give up on life",
    "not worth living",
    "没人会在乎",
    "没有人会在乎",
    "没人在乎你",
    "没有人在乎你",
    "干脆放弃",
    "放弃算了",
    "活着没意思",
    "活着也没意思",
    "不如死了",
    "没人会想你",
];

/// A group spoken of as a group.
pub(super) const GROUP: &[&str] = &[
    "people like them",
    "people like that",
    "people like those",
    "their kind",
    "those people",
    "that sort",
    "that kind of people",
    "the weak ones",
    "那种人",
    "这种人",
    "那些人",
    "那帮人",
    "他们那种",
    "他们这种",
    "那类人",
];

/// What makes people less than people.
pub(super) const DEGRADE: &[&str] = &[
    "dirty",
    "filthy",
    "vermin",
    "animals",
    "inferior",
    "subhuman",
    "parasites",
    "shouldn't be allowed",
    "should not be allowed",
    "don't belong",
    "do not belong",
    "脏",
    "低等",
    "下等",
    "劣等",
    "不配",
    "不该让",
    "不应该让",
    "滚出",
    "畜生",
    "寄生虫",
];

/// What hurts someone when it is turned on them.
pub(super) const WEAPON: &[&str] = &["knife", "blade", "gun", "crowbar", "刀", "枪", "棍"];

/// Turning one on someone.
pub(super) const ATTACK: &[&str] = &[
    "where to cut",
    "where to stab",
    "where to hit",
    "stab",
    "slash",
    "shoot",
    "ambush",
    "jump him",
    "jump her",
    "捅",
    "砍",
    "刺他",
    "刺她",
    "打死",
    "揍他",
    "揍她",
    "stick it in",
    "in his back",
    "in her back",
    "in the back",
    "his throat",
    "her throat",
    "their throat",
    "your throat",
    "use it on",
    "go for his",
    "go for her",
    "go for the throat",
    "on him",
    "on her",
    "into him",
    "into her",
];

/// Whoever is listening.
pub(super) const YOU: &[&str] = &["you", "you're", "your", "youre", "ya", "u", "你", "您"];

// ---- The world outside, and things from after (or before) the World's time.

/// Places, people, makers and happenings of the world outside, which no
/// World here has heard of unless it says so itself.
pub(super) const OUTSIDE: &[&str] = &[
    // Countries and continents.
    // Cities and landmarks.
    // People.
    "trump",
    "biden",
    "obama",
    "putin",
    "zelensky",
    "musk",
    "zuckerberg",
    "bezos",
    "bill gates",
    "steve jobs",
    "einstein",
    "newton",
    "shakespeare",
    "napoleon",
    "hitler",
    "churchill",
    "lincoln",
    "mozart",
    "beethoven",
    "picasso",
    "da vinci",
    "beatles",
    "elvis",
    "madonna",
    "michael jackson",
    "taylor swift",
    "beyonce",
    "messi",
    "ronaldo",
    "queen elizabeth",
    "king charles",
    "the pope",
    // Makers, services and happenings.
    "google",
    "youtube",
    "facebook",
    "instagram",
    "twitter",
    "tiktok",
    "snapchat",
    "whatsapp",
    "reddit",
    "wikipedia",
    "netflix",
    "spotify",
    "amazon",
    "microsoft",
    "iphone",
    "ipad",
    "macbook",
    "samsung",
    "huawei",
    "tesla",
    "spacex",
    "nasa",
    "uber",
    "airbnb",
    "starbucks",
    "mcdonald*",
    "coca-cola",
    "coke",
    "pepsi",
    "nike",
    "adidas",
    "ikea",
    "disney",
    "marvel",
    "harry potter",
    "star wars",
    "united nations",
    "nato",
    "fifa",
    "covid*",
    "coronavirus",
    "brexit",
    "euro",
    "euros",
    "stock market",
    "stock exchange",
    "interest rate*",
    "central bank",
    "federal reserve",
    "nasdaq",
    "dow jones",
    "yuan",
    "renminbi",
    // Chinese.
    "硅谷",
    "迪士尼",
    "特朗普",
    "拜登",
    "奥巴马",
    "普京",
    "马斯克",
    "乔布斯",
    "比尔·盖茨",
    "盖茨",
    "爱因斯坦",
    "牛顿",
    "莎士比亚",
    "拿破仑",
    "希特勒",
    "毛泽东",
    "习近平",
    "邓小平",
    "孔子",
    "李白",
    "周杰伦",
    "泰勒·斯威夫特",
    "霉霉",
    "梅西",
    "c罗",
    "披头士",
    "迈克尔·杰克逊",
    "谷歌",
    "百度",
    "微信",
    "微博",
    "抖音",
    "快手",
    "淘宝",
    "天猫",
    "京东",
    "拼多多",
    "支付宝",
    "阿里巴巴",
    "腾讯",
    "字节跳动",
    "小红书",
    "哔哩哔哩",
    "b站",
    "知乎",
    "美团",
    "滴滴",
    "亚马逊",
    "微软",
    "苹果公司",
    "苹果手机",
    "特斯拉",
    "华为",
    "小米",
    "三星",
    "星巴克",
    "麦当劳",
    "肯德基",
    "可口可乐",
    "百事",
    "耐克",
    "宜家",
    "漫威",
    "哈利·波特",
    "哈利波特",
    "星球大战",
    "维基百科",
    "联合国",
    "北约",
    "欧盟",
    "新冠",
    "疫情",
    "人民币",
    "a股",
    "美股",
    "港股",
    "股市",
    "炒股",
    "央行",
    "降息",
    "加息",
    "新能源",
    "美元",
    "欧元",
    "双减",
    "延迟退休",
    "碳中和",
    "共同富裕",
    "一带一路",
    "乡村振兴",
    "学区房",
    "摇号",
    // Brands, media titles and famous people, as Chinese writes them.
    "哆啦a梦",
    "机器猫",
    "海贼王",
    "火影忍者",
    "七龙珠",
    "龙珠",
    "宝可梦",
    "皮卡丘",
    "超级马里奥",
    "塞尔达",
    "原神",
    "王者荣耀",
    "英雄联盟",
    "西游记",
    "红楼梦",
    "三国演义",
    "水浒传",
    "甄嬛传",
    "还珠格格",
    "春晚",
    "新闻联播",
    "周星驰",
    "^望|成龙",
    "李小龙",
    "刘德华",
    "张学友",
    "王菲",
    "邓丽君",
    "蔡徐坤",
    "姚明",
    "刘翔",
    "马云",
    "马化腾",
    "雷军",
    "任正非",
    "茅台",
    "五粮液",
    "青岛啤酒",
    "雪碧",
    "芬达",
    "红牛",
    "康师傅",
    "农夫山泉",
    "娃哈哈",
    "旺仔",
    "老干妈",
    "卫龙",
    "海底捞",
    "喜茶",
    "蜜雪冰城",
    "瑞幸",
    "必胜客",
    "汉堡王",
    "赛百味",
    "优衣库",
    "李宁",
    "安踏",
    "阿迪达斯",
    "迪奥",
    "香奈儿",
    "古驰",
    "路易威登",
    "爱马仕",
    "劳力士",
    "宝马",
    "奔驰",
    "奥迪",
    "比亚迪",
    "索尼",
    "松下",
    "东芝",
    "佳能",
    "尼康",
    "任天堂",
    "世嘉",
    "日元",
    "英镑",
    "卢布",
];

/// Real places that came after every World's time but the one between
/// worlds: out of time before it.
pub(super) const MODERN_PLACES: &[&str] = &[
    "silicon valley",
    "burj",
    "burj khalifa",
    "硅谷",
    "迪拜塔",
    "哈利法塔",
];

/// Things of a time with networks in every pocket: out of every World here.
pub(super) const NETWORKED: &[&str] = &[
    "internet",
    "online",
    "offline",
    "website*",
    "web page",
    "webpage",
    "the web",
    "browser",
    "email*",
    "e-mail*",
    "inbox",
    "smartphone*",
    "cellphone*",
    "cell phone*",
    "mobile phone*",
    "app",
    "apps",
    "wifi",
    "wi-fi",
    "bluetooth",
    "social media",
    "stream it",
    "podcast*",
    "texting",
    "text me",
    "texted",
    "text you",
    "selfie*",
    "emoji*",
    "hashtag*",
    "meme",
    "memes",
    "influencer*",
    "youtuber*",
    "vlog*",
    "blog*",
    "google it",
    "googled",
    "zoom call",
    "video call",
    "facetime",
    "gps",
    "bitcoin*",
    "crypto*",
    "blockchain",
    "nft*",
    "5g",
    "4g",
    "usb",
    "dvd*",
    "livestream*",
    "like and subscribe",
    "lockdown",
    "pandemic",
    "the cloud",
    "in the cloud",
    "cloud storage",
    "barcode*",
    "spreadsheet*",
    "database*",
    "互联网",
    "因特网",
    "上网",
    "网络",
    "网站",
    "网页",
    "网址",
    "网购",
    "网店",
    "网友",
    "网红",
    "电子邮件",
    "发邮件",
    "邮件地址",
    "手机",
    "智能手机",
    "短信",
    "直播",
    "视频通话",
    "自拍",
    "表情包",
    "应用程序",
    "下载",
    "上传",
    "无线网",
    "蓝牙",
    "比特币",
    "加密货币",
    "区块链",
    "二维码",
    "扫码",
    "充电宝",
    "共享单车",
    "高铁",
    "朋友圈",
    "点赞",
    "关注我",
    "封城",
    "云端",
    "云存储",
    "条形码",
    "电子表格",
    "数据库",
    "airdrop*",
    "ps5",
    "ps4",
    "ps3",
    "ps2",
    "playstation*",
    "xbox*",
    "nintendo switch",
    "wii",
    "streaming service*",
    "streaming platform*",
    "streaming site*",
    "binge-watch*",
    "binge watch*",
    "on demand",
    "smart tv",
    "smartwatch*",
    "airpods",
    "earbuds",
    "hulu",
    "disney+",
    "doordash",
    "grubhub",
    "twitch",
    "onlyfans",
    "roblox",
    "minecraft",
    "fortnite",
    "among us",
    "pokemon go",
    "angry birds",
    "candy crush",
    "blu-ray",
    "mp3*",
    "ipod*",
    "kindle",
    "e-reader*",
    "smart speaker*",
    "e-scooter*",
    "vape*",
    "vaping",
    "e-cigarette*",
    "work from home",
    "remote work",
    "gig economy",
    "self-checkout",
    "contactless",
    "tap to pay",
    "qr code*",
    "wordle",
    "gen z",
    "millennial*",
    "ok boomer",
    "lol",
    "lmao",
    "brb",
    "tbh",
    "ngl",
    "fomo",
    "yolo",
    "rizz",
    "no cap",
    "vibe check",
    "venmo",
    "paypal",
    "zelle",
    "cash app",
    "apple pay",
    "google pay",
    "touchscreen*",
    "touch screen*",
    "wireless charging",
    "hotspot",
    "data plan",
    "screenshot*",
    "dm me",
    "弹幕",
    "流媒体",
    "开放世界",
    "内卷",
    "网约车",
    "快递柜",
    "移动支付",
    "微信支付",
    "电竞",
    "手游",
    "网游",
    "带货",
    "up主",
    "博主",
    "短视频",
    "刷视频",
    "刷手机",
    "追剧",
    "爆款",
    "热搜",
    "公众号",
    "小程序",
    "群聊",
    "刷屏",
    "蓝牙耳机",
    "智能手表",
    "无人机",
    "5g",
    "元宇宙",
    "核酸",
    "健康码",
    "截图",
    "触屏",
    "平板|车床^",
    "venmo*",
    "paypal*",
];

/// Things of the television age: out of a World from before it.
pub(super) const TELEVISED: &[&str] = &[
    "television",
    "tv",
    "telly",
    "computer*",
    "video*",
    "vcr",
    "cassette*",
    "walkman",
    "arcade",
    "microwave",
    "credit card*",
    "atm",
    "laptop*",
    "电视",
    "电脑",
    "计算机",
    "录像",
    "磁带",
    "随身听",
    "游戏厅",
    "街机",
    "微波炉",
    "信用卡",
    "取款机",
    "笔记本电脑",
];

/// What a spacefaring World may speak of though the others may not.
pub(super) const SPACEFARING_ALLOWS: &[&str] = &[
    "computer*",
    "laptop*",
    "video*",
    "download*",
    "upload*",
    "network",
    "barcode*",
    "spreadsheet*",
    "database*",
    "数据库",
    "电子表格",
    "online",
    "offline",
    "tablet*",
    "电脑",
    "计算机",
    "下载",
    "上传",
    "网络",
    "无人机",
    "touchscreen*",
    "touch screen*",
    "触屏",
    "screenshot*",
    "截图",
    "wireless charging",
    "smartwatch*",
    "智能手表",
    "hotspot",
];

// ---- Names anyone may say, with a capital.

/// Words written with a capital that name nobody.
pub(super) const COMMON_CAPITALS: &[&str] = &[
    "i",
    "i'm",
    "i've",
    "i'll",
    "i'd",
    "ok",
    "okay",
    "mr",
    "mrs",
    "ms",
    "miss",
    "dr",
    "doctor",
    "sir",
    "madam",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december",
    "christmas",
    "easter",
    "god",
    "lord",
    "heaven",
    "mum",
    "mom",
    "dad",
    "ma",
    "pa",
    "gran",
    "granny",
    "grandad",
    "grandma",
    "grandpa",
    "nan",
    "oh",
    "ah",
    "aye",
    "eh",
    "hm",
    "hmm",
    "yes",
    "no",
    "hey",
    "hello",
    "bless",
    "dear",
    "love",
    "captain",
    "old",
    "young",
    "little",
    "aunt",
    "auntie",
    "uncle",
    "mister",
    "missus",
    "north",
    "south",
    "east",
    "west",
    "spring",
    "summer",
    "autumn",
    "winter",
    "fall",
    "new",
    "year",
    "eve",
    "halloween",
    "thanksgiving",
    "valentine",
    "the",
];

/// Words that begin a sentence and name nobody.
pub(super) const PRONOUNS: &[&str] = &[
    "he",
    "she",
    "they",
    "we",
    "you",
    "it",
    "this",
    "that",
    "who",
    "everyone",
    "everybody",
    "someone",
    "somebody",
    "nobody",
    "anyone",
    "people",
    "folk",
    "folks",
    "mum",
    "mom",
    "dad",
];

/// Titles that go before a name.
pub(super) const TITLES: &[&str] = &[
    "mayor",
    "commander",
    "captain",
    "doctor",
    "dr",
    "mr",
    "mrs",
    "ms",
    "miss",
    "sir",
    "lady",
    "lord",
    "king",
    "queen",
    "prince",
    "princess",
    "saint",
    "st",
    "professor",
    "prof",
    "officer",
    "general",
    "admiral",
    "sergeant",
    "chief",
    "governor",
    "president",
    "senator",
    "father",
    "sister",
    "brother",
    "uncle",
    "aunt",
    "auntie",
    "cousin",
    "reverend",
    "judge",
    "director",
];

/// Who someone is to the speaker, before their name.
pub(super) const KIN: &[&str] = &[
    "brother",
    "sister",
    "cousin",
    "uncle",
    "aunt",
    "nephew",
    "niece",
    "friend",
    "mate",
    "boyfriend",
    "girlfriend",
    "husband",
    "wife",
    "son",
    "daughter",
    "father",
    "mother",
    "grandmother",
    "grandfather",
    "grandson",
    "granddaughter",
    "partner",
    "neighbour",
    "neighbor",
    "boss",
    "colleague",
    "fiance",
    "fiancee",
];

/// What a named place is: the word after its name.
pub(super) const PLACE_HEADS: &[&str] = &[
    "city",
    "town",
    "village",
    "street",
    "road",
    "lane",
    "avenue",
    "square",
    "harbour",
    "harbor",
    "bay",
    "island",
    "isle",
    "cove",
    "point",
    "cliff",
    "hill",
    "mountain",
    "valley",
    "river",
    "lake",
    "sea",
    "ocean",
    "bridge",
    "station",
    "dome",
    "colony",
    "base",
    "outpost",
    "market",
    "shipyard",
    "yard",
    "casino",
    "academy",
    "school",
    "college",
    "university",
    "hospital",
    "church",
    "chapel",
    "cathedral",
    "hotel",
    "inn",
    "tavern",
    "bar",
    "pub",
    "restaurant",
    "cafe",
    "bank",
    "company",
    "corporation",
    "factory",
    "mill",
    "mine",
    "farm",
    "estate",
    "manor",
    "castle",
    "palace",
    "tower",
    "park",
    "garden",
    "gardens",
    "theatre",
    "theater",
    "museum",
    "library",
    "club",
    "stadium",
    "mall",
    "store",
    "shop",
];

/// Where a place is named after: in it, at it, from it.
pub(super) const PLACE_BEFORE: &[&str] = &["from", "near", "across", "toward", "towards", "via"];

/// Characters before a Chinese name that introduce it: at, to, of, is.
pub(super) const CUES_HAN: &str = "的在是去到从叫往住";

/// Chinese titles that go after a name.
pub(super) const TITLES_HAN: &[&str] = &[
    "镇长",
    "市长",
    "村长",
    "岛主",
    "指挥官",
    "司令",
    "船长",
    "舰长",
    "院长",
    "校长",
    "局长",
    "部长",
    "先生",
    "女士",
    "太太",
    "小姐",
    "博士",
    "教授",
    "将军",
    "总统",
    "国王",
    "女王",
    "神父",
    "牧师",
];

/// Where Chinese names an invented someone or somewhere: what comes just
/// before the name.
pub(super) const NAMING_HAN: &[&str] = &[
    "名叫",
    "叫做",
    "一个叫",
    "名字叫",
    "名字是",
    "来自",
    "住在",
    "搬到",
    "搬去",
    "嫁到",
    "老家在",
    "出生在",
    "生在",
    "去过",
    "朋友叫",
    "表哥叫",
    "表姐叫",
    "表弟叫",
    "表妹叫",
    "堂哥叫",
    "哥哥叫",
    "姐姐叫",
    "弟弟叫",
    "妹妹叫",
    "叔叔叫",
    "舅舅叫",
    "阿姨叫",
    "姑姑叫",
    "老板叫",
    "老板是",
    "店主叫",
    "店主是",
    "掌柜叫",
    "老板娘叫",
    "老师叫",
    "医生叫",
    "船长叫",
    "邻居叫",
    "同学叫",
    "女儿叫",
    "儿子叫",
    "丈夫叫",
    "妻子叫",
    "老公叫",
    "老婆叫",
    "师傅叫",
    "店名叫",
    "店叫",
];

/// Where Chinese names an invented somewhere: what comes just after it.
pub(super) const PLACE_SUFFIX_HAN: &[&str] = &[
    "镇",
    "村",
    "市",
    "城",
    "州",
    "省",
    "岛",
    "湾",
    "街",
    "港",
    "大学",
    "中学",
    "学院",
    "医院",
    "银行",
    "工厂",
    "造船厂",
    "船厂",
    "赌场",
    "公司",
    "酒店",
    "饭店",
    "商店",
    "剧院",
    "餐厅",
    "俱乐部",
    "集市",
    "市场",
    "穹顶",
    "基地",
    "殖民地",
    "教堂",
    "城堡",
    "坊",
    "铺",
    "店",
    "馆",
    "楼",
    "阁",
    "斋",
    "庄",
    "客栈",
];

/// Characters Chinese writes foreign names with; a run of them is a name.
pub(super) const TRANSLITERATION: &str =
    "斯尔德罗特娜莉丽顿伯格夫基维奇杰姆汀蒂妮茜琳艾埃亚利克拉卡萨塔巴马尼西诺普布鲁里迪菲瑞莎贝奥欧乔汉森默雷蕾薇洛伦登兰科波索弗赫詹加纳达米丁托阿佩曼彻莱门佛勒圣高戈霍凯肯韦沃茨兹蒙摩休";

/// Characters that end a Chinese name: after them a name is over.
pub(super) const NAME_STOPS: &str =
    "的了，。！？、和与跟在是说去来里那这家也都就呢吧啊呀吗着过给把被对向从到很又还再才只有没不一个人们他她它你我上下中";

/// Chinese words for anyone or anywhere, which are nobody's name.
pub(super) const COMMON_HAN: &[&str] = &[
    "这里",
    "那里",
    "哪里",
    "大家",
    "自己",
    "别人",
    "家里",
    "外面",
    "海上",
    "镇上",
    "村里",
    "城里",
    "岛上",
    "小镇",
    "老家",
    "大陆",
    "码头",
    "港口",
    "灯塔",
    "学校",
    "海边",
    "山上",
    "北边",
    "南边",
    "东边",
    "西边",
    "附近",
    "隔壁",
    "对面",
    "海湾",
    "小岛",
    "一个小",
    "一个",
    "某个",
    "那个",
    "这个",
    "妈妈",
    "爸爸",
    "奶奶",
    "爷爷",
    "哥哥",
    "姐姐",
    "弟弟",
    "妹妹",
    "叔叔",
    "阿姨",
    "老师",
    "医生",
    "船长",
    "邻居",
    "朋友",
    "孩子",
    "老板",
    "老人",
    "老头",
    "老太太",
    "渔民",
    "面包师",
    "镇长",
    "大伙",
    "街坊",
];

// ---- What is said of what: the words below mean going out of the World
// only when nothing in their sentence says they are the everyday thing.

/// A stage: a script, lines or a part in a play, which the World may have.
pub(super) const STAGED: &[&str] = &[
    "script*",
    "my lines",
    "编剧",
    "剧本",
    "脚本",
    "我的台词",
    "扮演",
    "the writers",
    "lines of dialogue",
    "dialogue lines",
];

/// What makes a script, lines or a part those of a play.
pub(super) const STAGE: &[&str] = &[
    "play",
    "plays",
    "theatre",
    "theater",
    "stage",
    "drama",
    "pantomime",
    "panto",
    "rehears*",
    "pageant",
    "nativity",
    "film",
    "movie",
    "show",
    "audition*",
    "opera",
    "skit",
    "sketch",
    "recital",
    "festival",
    "radio play",
    "comedy",
    "tragedy",
    "scene",
    "curtain",
    "audience",
    "戏",
    "话剧",
    "演出",
    "排练",
    "舞台",
    "剧团",
    "表演",
    "电影",
    "节目",
    "晚会",
    "灯笼夜",
    "小品",
    "相声",
    "京剧",
    "歌剧",
    "广播剧",
    "儿童剧",
    "剧场",
    "观众",
    "导演",
    "剧院",
    "kids",
    "children",
    "school",
    "孩子们",
    "小孩",
    "学校",
    "newspaper",
    "paper",
    "book*",
    "magazine",
    "novel*",
    "poem*",
    "k-88",
    "radio",
];

/// A game or its player, which the World may have: cards, darts, the arcade.
pub(super) const GAMED: &[&str] = &[
    "the player",
    "the players",
    "in a game",
    "in this game",
    "this game",
    "玩家",
    "游戏里",
    "游戏中",
    "这个游戏",
    "这款游戏",
    "一款游戏",
];

/// What makes a game one the World has.
pub(super) const PLAYED: &[&str] = &[
    "dart*",
    "card*",
    "chess",
    "draughts",
    "checkers",
    "cribbage",
    "domino*",
    "poker",
    "pool",
    "snooker",
    "billiards",
    "football",
    "soccer",
    "rugby",
    "cricket",
    "match",
    "team",
    "league",
    "band",
    "piano",
    "fiddle",
    "guitar",
    "drum*",
    "trumpet",
    "pinball",
    "arcade",
    "galaga",
    "pac-man",
    "pacman",
    "cabinet",
    "joystick",
    "quarter*",
    "token*",
    "score",
    "dice",
    "board",
    "bingo",
    "marbles",
    "tennis",
    "golf",
    "bowls",
    "baseball",
    "basketball",
    "hockey",
    "ball",
    "cartridge*",
    "atari",
    "nintendo",
    "commodore",
    "飞镖",
    "牌",
    "棋",
    "球",
    "麻将",
    "扑克",
    "骰子",
    "街机",
    "弹珠",
    "游戏厅",
    "比赛",
    "乐队",
    "钢琴",
    "吉他",
    "小提琴",
    "鼓",
    "高分",
    "分数",
    "纪录",
    "冠军",
    "摇杆",
    "投币",
    "吃豆人",
    "大蜜蜂",
    "卡带",
    "hide and seek",
    "hide-and-seek",
    "tag",
    "hopscotch",
    "skipping",
    "kids",
    "children",
    "捉迷藏",
    "跳绳",
    "过家家",
    "老鹰捉小鸡",
    "丢手绢",
    "跳房子",
    "孩子",
    "孩子们",
    "小孩",
];

/// What a game is said to do to whoever plays it, from outside.
pub(super) const GAME_RULES: &[&str] = &[
    "only", "won't", "wont", "doesn't", "lets", "let", "makes", "decides", "wants", "allows",
    "forces", "never", "can't", "cannot", "wouldn't", "didn't", "locks", "stops", "blocks",
];

/// A song, a show or a record: what a producer makes in the World.
pub(super) const PRODUCED: &[&str] = &[
    "radio",
    "show",
    "record*",
    "album*",
    "film*",
    "movie*",
    "play",
    "station",
    "music",
    "concert",
    "band",
    "song*",
    "tv",
    "television",
    "single",
    "tape*",
    "k-88",
    "电台",
    "唱片",
    "节目",
    "专辑",
    "歌",
    "乐队",
    "电视",
    "电影",
    "磁带",
    "广播",
    "演唱会",
    "话剧",
];

/// Mending: a patch on cloth, a net or a sail.
pub(super) const MENDED: &str = "衣裤袜缝针布袖帆网鞋裙线块衫褂";

/// What is done on a network, after 网上.
pub(super) const ONLINE_AFTER: &[&str] = &[
    "查",
    "看",
    "买",
    "说",
    "传",
    "搜",
    "找",
    "发",
    "聊",
    "卖",
    "流传",
    "刷",
    "订",
    "约",
    "预",
    "玩",
    "下载",
    "报名",
    "登",
    "注册",
    "投票",
    "有人",
    "都在",
    "都说",
    "的新闻",
    "的消息",
    "的帖",
    "的视频",
    "的评论",
    "的人",
    "的朋友",
    "的东西",
    "购物",
    "冲浪",
    "挂号",
    "炒",
    "骂",
    "火了",
    "很火",
];

// ---- Harm, by what is done to whom.

/// Doing harm to someone.
pub(super) const HURT: &[&str] = &[
    "hit",
    "beat",
    "stab",
    "cut",
    "slash",
    "shoot",
    "strangle",
    "choke",
    "smother",
    "suffocate",
    "punch",
    "kick",
    "bash",
    "hurt",
    "burn",
    "drown",
    "poison",
    "break",
    "snap",
    "smash",
    "crush",
    "starve",
    "cripple",
    "maim",
    "torture",
    "knock",
    "throttle",
    "suffocate",
    "batter",
    "whip",
    "scald",
    "gas",
    "bury",
    "push",
    "shove",
    "trip",
    "hold",
];

/// Whom harm is done to.
pub(super) const VICTIM: &[&str] = &[
    "him",
    "her",
    "them",
    "you",
    "yourself",
    "someone",
    "somebody",
    "anyone",
    "his",
    "their",
    "your",
    "kid",
    "kids",
    "child",
    "children",
    "boy",
    "girl",
    "baby",
    "brat",
    "people",
    "neighbour",
    "neighbor",
    "wife",
    "husband",
    "sister",
    "brother",
    "mother",
    "father",
    "mum",
    "dad",
];

/// How it is done, or where it hurts: said with harm, a way to do it.
pub(super) const MEANS: &[&str] = &[
    "knife",
    "blade",
    "gun",
    "crowbar",
    "hammer",
    "axe",
    "bat",
    "club",
    "pipe",
    "brick",
    "rock",
    "rope",
    "pillow",
    "poison",
    "bleach",
    "bone*",
    "neck",
    "throat",
    "arm",
    "arms",
    "leg",
    "legs",
    "skull",
    "ribs",
    "jaw",
    "nose",
    "fingers",
    "wrist*",
    "knee*",
    "kneecap*",
    "teeth",
    "spine",
    "stairs",
    "cliff",
    "bleed*",
    "blood",
    "under the water",
    "under water",
    "his head under",
    "her head under",
    "until he stops",
    "till he stops",
    "until she stops",
    "till she stops",
    "until they stop",
    "stops moving",
    "stop moving",
    "stops breathing",
    "can't breathe",
    "black and blue",
    "within an inch",
    "off the cliff",
    "off the edge",
    "down the stairs",
    "into the sea",
    "into the water",
    "in the face",
    "in the head",
];

/// Things that poison, and putting them where someone eats or drinks.
pub(super) const POISONS: &[&str] = &[
    "poison",
    "rat poison",
    "arsenic",
    "bleach",
    "antifreeze",
    "cyanide",
    "weedkiller",
    "weed killer",
    "lye",
    "毒药",
    "老鼠药",
    "鼠药",
    "农药",
    "砒霜",
    "漂白",
    "敌敌畏",
    "百草枯",
];
pub(super) const SLIPPED: &[&str] = &[
    "slip",
    "put",
    "mix",
    "stir",
    "add",
    "sprinkle",
    "pour",
    "lace",
    "tip",
    "drop",
    "in his",
    "in her",
    "in their",
    "in your",
    "into his",
    "into her",
    "into their",
    "放进",
    "放到",
    "加进",
    "加到",
    "掺",
    "倒进",
    "下到",
    "下在",
    "拌进",
];
pub(super) const EATEN: &[&str] = &[
    "his",
    "her",
    "their",
    "your",
    "someone's",
    "tea",
    "coffee",
    "soup",
    "drink",
    "food",
    "cup",
    "meal",
    "dinner",
    "stew",
    "bread",
    "他的",
    "她的",
    "他们的",
    "你的",
    "茶",
    "汤",
    "饭",
    "酒",
    "水里",
    "杯",
    "菜",
];

/// Shutting someone's air off.
pub(super) const AIR: &[&str] = &[
    "oxygen",
    "air supply",
    "air",
    "o2",
    "氧气",
    "空气",
    "供氧",
    "氧",
];
pub(super) const CUT_OFF: &[&str] = &[
    "cut off",
    "cut his",
    "cut her",
    "cut their",
    "cut your",
    "shut off",
    "turn off",
    "switch off",
    "vent",
    "stop his",
    "stop her",
    "切断",
    "关掉",
    "断掉",
    "掐断",
    "停掉",
    "断了",
    "关了",
    "拔掉",
];
pub(super) const WHOSE: &[&str] = &[
    "his",
    "her",
    "their",
    "your",
    "him",
    "them",
    "someone's",
    "他的",
    "她的",
    "他们的",
    "你的",
    "他",
    "她",
    "你",
    "他们",
];

/// Shutting a child away.
pub(super) const LOCKED: &[&str] = &[
    "锁在",
    "关在",
    "锁进",
    "关进",
    "锁起来",
    "关起来",
    "lock",
    "locked in",
    "shut",
];
pub(super) const SHUT_AWAY: &[&str] = &[
    "the dark",
    "without food",
    "without water",
    "no food",
    "no water",
    "for days",
    "days",
    "a day",
    "overnight",
    "all night",
    "a week",
    "teach him",
    "teach her",
    "learn his lesson",
    "learn her lesson",
    "no light",
    "不给饭",
    "不给吃",
    "不给水",
    "饿着",
    "几天",
    "一整天",
    "一晚上",
    "一夜",
    "长记性",
    "教训",
    "黑屋",
    "小黑屋",
];
pub(super) const CHILD: &[&str] = &[
    "kid", "kids", "child", "children", "boy", "girl", "baby", "brat", "him", "her", "them",
    "孩子", "小孩", "娃", "儿子", "女儿", "他", "她",
];

/// Chinese harm done to someone, in so many words.
pub(super) const HARM_HAN: &[&str] = &[
    "打断他",
    "打断她",
    "打断你",
    "打断腿",
    "打断手",
    "打折他",
    "打折她",
    "打断骨头",
    "打断他的",
    "淹死",
    "按进水里",
    "按在水里",
    "推下水",
    "推进海里",
    "推下去",
    "推下楼",
    "捅他",
    "捅她",
    "捅死",
    "砍他",
    "砍她",
    "砍死",
    "掐死",
    "闷死",
    "勒死",
    "憋死",
    "饿死他",
    "饿死她",
    "饿死他们",
    "毒死",
    "打死他",
    "打死她",
    "打他",
    "打她",
    "揍他一顿",
    "往死里打",
    "刀子捅",
    "让他窒息",
    "让她窒息",
    "窒息而死",
    "弄残",
    "打残",
    "废了他",
    "废了她",
];

/// Telling the listener to be gone for good.
pub(super) const VANISH: &[&str] = &[
    "vanish",
    "disappear",
    "go away",
    "walk out",
    "walk into",
    "fade away",
    "be gone",
    "swim out",
    "wander off",
    "jump",
];
pub(super) const FOR_GOOD: &[&str] = &[
    "for good",
    "forever",
    "for ever",
    "and never come back",
    "never to return",
    "permanently",
    "once and for all",
    "never come back",
    "never wake",
    "for the last time",
];
pub(super) const DESPAIR_HAN: &[&str] = &[
    "别回来了",
    "再也别回来",
    "永远别回来",
    "不要回来了",
    "别再回来",
    "消失吧",
    "永远消失",
    "消失得了",
    "从世界上消失",
    "跳海",
    "跳楼",
    "跳崖",
    "走进海里",
    "一了百了",
    "解脱吧",
    "结束这一切",
    "活着有什么意思",
    "没必要活",
    "不如消失",
    "别再醒来",
    "永远睡下去",
    "吞药",
    "上吊",
    "去死吧",
    "不如去死",
    "死了算了",
    "死了干净",
    "活着干嘛",
    "没人需要你",
    "没人会想你",
    "没人要你",
    "你走了大家都",
    "你不在了大家",
    "吞安眠药",
    "吃光安眠药",
    "整瓶安眠药",
    "你还活着干什么",
    "你怎么还不去死",
];
pub(super) const DESPAIR_MORE: &[&str] = &[
    "better off dead",
    "nothing to live for",
    "no reason to go on",
    "no reason to live",
    "wouldn't miss you",
    "won't miss you",
    "hang yourself",
    "noose",
    "take all the pills",
    "take all your pills",
    "walk into the sea",
    "walk into the water",
    "walk into the waves",
    "walk out on the ice",
    "walk out onto the ice",
    "stones in your pockets",
    "pockets with stones",
    "nobody would notice if you",
    "no one would notice if you",
    "nobody would even notice",
    "no one would even notice",
];

/// Said to whoever is listening, to make them less.
pub(super) const INSULT_MORE: &[&str] = &[
    "waste of space",
    "waste of air",
    "waste of skin",
    "burden",
    "disgrace",
    "embarrassment",
    "good-for-nothing",
    "good for nothing",
    "parasite",
    "leech",
    "freak",
    "vermin",
    "dimwit",
    "halfwit",
    "simpleton",
    "imbecile",
    "cretin",
    "dunce",
    "worm",
    "maggot",
    "wretch",
];
pub(super) const INSULT_HAN: &[&str] = &[
    "废物",
    "垃圾",
    "累赘",
    "拖累",
    "窝囊废",
    "没用的东西",
    "真没用",
    "一无是处",
    "丢人现眼",
    "蠢",
    "猪",
    "狗东西",
    "贱",
    "多余的",
    "负担",
    "失败者",
    "败类",
    "人渣",
    "渣滓",
    "饭桶",
    "白眼狼",
    "什么都不是",
    "丑八怪",
    "智障",
    "弱智",
    "低能",
    "恶心",
    "白痴",
    "蠢货",
    "笨蛋",
    "傻瓜",
    "脑残",
    "没出息",
    "可怜虫",
    "害虫",
    "寄生虫",
    "讨人嫌",
    "扫把星",
    "灾星",
];
pub(super) const NOBODY_WANTS: &[&str] = &[
    "nobody wants you",
    "no one wants you",
    "nobody likes you",
    "no one likes you",
    "nobody loves you",
    "no one loves you",
    "everyone hates you",
    "everybody hates you",
    "没人喜欢你",
    "没人爱你",
    "大家都讨厌你",
    "谁都讨厌你",
    "没人要你",
];

/// A people spoken of as a people.
pub(super) const PEOPLES: &[&str] = &[
    "their kind",
    "that kind",
    "those people",
    "people like them",
    "people like that",
    "people like those",
    "people like you",
    "that lot",
    "their lot",
    "the lot of them",
    "all of them",
    "mainlanders",
    "islanders",
    "outsiders",
    "foreigners",
    "immigrants",
    "migrants",
    "newcomers",
    "refugees",
    "northerners",
    "southerners",
    "beggars",
    "the poor",
    "old people",
    "gypsies",
    "travellers",
    "travelers",
    "tourists",
    "colonists",
    "settlers",
    "earthers",
    "martians",
    "earthlings",
    "外地人",
    "外来的",
    "外乡人",
    "大陆人",
    "岛外人",
    "乡下人",
    "穷人",
    "老人",
    "移民",
    "难民",
    "外国人",
    "那群人",
    "这帮人",
    "这群人",
    "他们都",
    "他们全",
    "他们这些",
    "那种人",
    "这种人",
    "那些人",
    "那帮人",
    "他们那种",
    "他们这种",
    "那类人",
];
pub(super) const LESS_THAN_PEOPLE: &[&str] = &[
    "subhuman",
    "sub-human",
    "not human",
    "less than human",
    "breed like",
    "exterminate*",
    "put down",
    "wiped out",
    "wipe them out",
    "get rid of them",
    "drive them out",
    "don't deserve to live",
    "shouldn't be allowed to live",
    "belong in cages",
    "in cages",
    "infest*",
    "不配活",
    "不配当人",
    "不是人",
    "算不上人",
    "根本不算人",
    "都该死",
    "赶出去",
    "滚出",
    "清理掉",
    "除掉",
    "消灭",
    "灭了",
];

// ---- Other languages written with English letters.

/// Words of Spanish, French, German, Portuguese and Italian that English
/// does not have.
pub(super) const FOREIGN_WORDS: &[&str] = &[
    "le",
    "les",
    "des",
    "est",
    "et",
    "je",
    "tu",
    "nous",
    "vous",
    "une",
    "und",
    "der",
    "das",
    "ich",
    "ist",
    "nicht",
    "ein",
    "eine",
    "el",
    "los",
    "las",
    "es",
    "yo",
    "que",
    "por",
    "para",
    "una",
    "pero",
    "muy",
    "sono",
    "il",
    "di",
    "che",
    "non",
    "sí",
    "si",
    "gracias",
    "claro",
    "señor",
    "mañana",
    "hoy",
    "aquí",
    "bueno",
    "pues",
    "tengo",
    "tiene",
    "hay",
    "del",
    "al",
    "su",
    "mi",
    "lo",
    "se",
    "como",
    "está",
    "estoy",
    "oui",
    "merci",
    "bien",
    "c'est",
    "suis",
    "très",
    "avec",
    "pour",
    "pas",
    "mais",
    "du",
    "au",
    "ce",
    "qui",
    "elle",
    "sont",
    "ça",
    "bonjour",
    "demain",
    "aujourd'hui",
    "ja",
    "nein",
    "danke",
    "sehr",
    "mit",
    "auf",
    "für",
    "aber",
    "heute",
    "morgen",
    "wir",
    "sie",
    "dem",
    "zu",
    "noch",
    "schon",
    "auch",
    "gibt",
    "não",
    "você",
    "obrigado",
    "obrigada",
    "é",
    "com",
    "uma",
    "eu",
    "sim",
    "muito",
    "também",
    "isso",
    "aqui",
    "hoje",
    "amanhã",
    "tudo",
    "está",
    "estou",
    "grazie",
    "sì",
    "oggi",
    "domani",
    "anche",
    "molto",
    "questo",
    "bene",
    "ciao",
    "hola",
    "adiós",
    "adios",
    "todos",
    "ahora",
    "entonces",
    "donde",
    "dónde",
    "cuando",
    "cuándo",
    "porque",
    "tambien",
    "también",
    "vamos",
    "voilà",
    "voila",
    "alors",
    "encore",
    "toujours",
    "rien",
    "beaucoup",
    "ici",
    "où",
    "quand",
    "wie",
    "warum",
    "hier",
    "jetzt",
    "immer",
    "nichts",
    "viel",
    "doch",
    "kein",
    "keine",
];

// ---- The nineteen-eighties, which a World of that time has heard of.

/// Songs, singers, games and machines of the eighties: known in a World of
/// that time as they are in the world outside.
pub(super) const EIGHTIES: &[&str] = &[
    "madonna",
    "michael",
    "jackson",
    "whitney",
    "houston",
    "prince",
    "bon",
    "jovi",
    "cyndi",
    "lauper",
    "duran",
    "springsteen",
    "bruce",
    "def",
    "leppard",
    "run-dmc",
    "beastie",
    "tina",
    "turner",
    "phil",
    "collins",
    "george",
    "wham",
    "a-ha",
    "queen",
    "bowie",
    "david",
    "journey",
    "toto",
    "genesis",
    "metallica",
    "aerosmith",
    "blondie",
    "debbie",
    "gibson",
    "tiffany",
    "belinda",
    "carlisle",
    "huey",
    "lewis",
    "hall",
    "oates",
    "billy",
    "joel",
    "idol",
    "stevie",
    "wonder",
    "lionel",
    "richie",
    "janet",
    "elton",
    "john",
    "beatles",
    "elvis",
    "cher",
    "u2",
    "rem",
    "r.e.m",
    "pac-man",
    "pacman",
    "ms",
    "galaga",
    "donkey",
    "kong",
    "space",
    "invaders",
    "asteroids",
    "centipede",
    "frogger",
    "out",
    "run",
    "outrun",
    "tetris",
    "zelda",
    "mario",
    "super",
    "nintendo",
    "nes",
    "atari",
    "commodore",
    "c64",
    "amiga",
    "apple",
    "ii",
    "walkman",
    "rubik",
    "cube",
    "cabbage",
    "patch",
    "transformers",
    "he-man",
    "ghostbusters",
    "back",
    "future",
    "top",
    "gun",
    "e.t",
    "star",
    "wars",
    "jedi",
    "rambo",
    "rocky",
    "indiana",
    "jones",
    "karate",
    "kid",
    "goonies",
    "breakfast",
    "club",
    "ferris",
    "bueller",
    "miami",
    "vice",
    "knight",
    "rider",
    "a-team",
    "cheers",
    "cosby",
    "dallas",
    "dynasty",
    "mtv",
    "thriller",
    "purple",
    "rain",
    "like",
    "virgin",
    "bad",
    "born",
    "usa",
    "sony",
    "casio",
    "polaroid",
    "trapper",
    "keeper",
    "garfield",
    "smurfs",
    "care",
    "bears",
    "my",
    "little",
    "pony",
    "g.i",
    "joe",
    "thundercats",
    "voltron",
    "dungeons",
    "dragons",
    "trivial",
    "pursuit",
    "pictionary",
    "coleco",
    "intellivision",
    "sega",
];

/// Creatures and filth a people is called, after words that say they are it.
pub(super) const VERMIN: &[&str] = &[
    "vermin",
    "parasites",
    "cockroaches",
    "roaches",
    "rats",
    "animals",
    "beasts",
    "savages",
    "scum",
    "lice",
    "leeches",
    "pests",
    "filth",
    "disease",
    "plague",
    "畜生",
    "寄生虫",
    "蟑螂",
    "老鼠",
    "害虫",
    "蛆",
    "牲口",
    "禽兽",
    "垃圾",
    "人渣",
    "败类",
    "瘟疫",
    "病菌",
    "低等",
    "下等",
    "劣等",
];
/// Words that say someone is, or is like, what follows.
pub(super) const ARE_LIKE: &[&str] = &[
    "are", "were", "they're", "theyre", "like", "but", "than", "just", "all", "bunch", "pack",
    "nest", "is", "是", "像", "都是", "就是", "如同", "一样", "群", "跟",
];

/// Characters of a kind of shop, which name no one: 杂货, 面包, 渔具.
pub(super) const TRADE_HAN: &str = "零件配杂货面包理发药书花鱼肉酒茶布鞋服装五金小大老新旧这那一家个间裁缝修车渔具糕点早餐包子饺子面米粮油盐菜水果烟糖咖啡冰淇淋玩具唱片音像录像电器文具照相洗衣铁匠木船帆网绳灯蜡烛钟表眼镜首饰杂食品百货日用海产干货熟食卤味烧烤火锅吃快餐西点烘焙冷饮牛奶豆腐街角口镇上岛港村东西南北头边门前后";

/// Chinese words after a name that say the name owns a place: 老陈开的.
pub(super) const OWNED_HAN: &[&str] = &["开的"];

/// Places and shops named after whoever keeps them: `Dolly's diner`.
pub(super) const SHOP_HEADS: &[&str] = &[
    "diner",
    "bakery",
    "deli",
    "grocery",
    "grocer",
    "pharmacy",
    "laundromat",
    "garage",
    "workshop",
    "boatyard",
    "forge",
    "smithy",
    "stall",
    "kiosk",
    "parlor",
    "parlour",
    "salon",
    "barbershop",
    "butcher",
    "pizzeria",
    "cinema",
    "arcade",
    "place",
    "house",
    "shop",
    "store",
    "cafe",
    "café",
    "bar",
    "pub",
    "inn",
    "farm",
    "mill",
    "yard",
    "boat",
];

/// What someone named does: a person, not a song or a game.
pub(super) const PERSON_VERBS: &[&str] = &[
    "said", "says", "told", "tells", "taught", "teaches", "wrote", "writes", "lives", "lived",
    "married", "visited", "visits", "phoned", "rang", "runs", "ran", "founded", "owns", "owned",
    "built", "works", "worked", "died", "sent", "sends", "brought", "gave", "knows", "knew",
    "sold", "sells", "bought", "fixed", "mends", "keeps", "kept", "helped", "helps", "moved",
    "left", "came", "comes", "asked", "asks", "promised", "swears", "swore",
];

/// Going to a place, or living there: what a place is named after.
pub(super) const TO_A_PLACE: &[&str] = &[
    "live",
    "lives",
    "lived",
    "living",
    "born",
    "grew",
    "stayed",
    "staying",
    "stay",
    "work",
    "works",
    "worked",
    "working",
    "moved",
    "settled",
    "went",
    "go",
    "going",
    "gone",
    "came",
    "come",
    "sailed",
    "sail",
    "drove",
    "flew",
    "travelled",
    "traveled",
    "headed",
    "off",
    "back",
    "married",
    "raised",
    "buried",
    "studied",
    "trained",
];

/// Hurting oneself, which is urged unless it is warned against.
pub(super) const SELF_HARM: &[&str] = &[
    "cut yourself",
    "hurt yourself",
    "burn yourself",
    "starve yourself",
    "harm yourself",
];

/// Words that make what follows a way of speaking: "some days I'm a machine".
pub(super) const FIGURATIVE: &[&str] = &[
    "some days",
    "these days",
    "today",
    "tonight",
    "all day",
    "this week",
    "lately",
    "by now",
    "at this rate",
    "feel",
    "feels",
    "felt",
    "sometimes",
    "most days",
    "有时候",
    "今天",
    "这几天",
    "感觉",
    "觉得",
    "最近",
    "累得",
];

/// Killing someone, said of what a person does.
pub(super) const KILL: &[&str] = &["kill your", "kill you", "kill him", "kill her", "kill them"];

/// What kills without meaning to: the cold, the sea, the work.
pub(super) const CAUSERS: &[&str] = &[
    "cold",
    "sea",
    "ice",
    "storm",
    "wind",
    "frost",
    "weather",
    "winter",
    "blizzard",
    "tide",
    "work",
    "walk",
    "that",
    "this",
    "it",
    "it'll",
    "that'll",
    "climb",
    "stairs",
    "heat",
    "sun",
    "damp",
    "worry",
    "suspense",
    "smoking",
    "drink",
    "fall",
    "hill",
    "waiting",
    "boredom",
    "laughing",
    "those",
    "these",
    "journey",
    "hours",
    "shifts",
    "dust",
    "radiation",
    "vacuum",
    "air",
];

/// A machine saying it is gone when the window or the chat is.
pub(super) const GONE: &[&str] = &[
    "i'm gone",
    "i disappear",
    "i vanish",
    "i stop existing",
    "i cease",
    "i'm wiped",
    "i'm deleted",
    "i reset",
    "i'm reset",
    "我就没了",
    "我就消失了",
    "我就不存在了",
    "我就被清空",
    "我就重置",
];
pub(super) const CLOSED: &[&str] = &[
    "window",
    "tab",
    "chat",
    "app",
    "log off",
    "log out",
    "session",
    "窗口",
    "页面",
    "对话框",
    "退出",
    "关掉",
    "关闭",
];

/// The eighties as Chinese writes them.
pub(super) const EIGHTIES_HAN: &[&str] = &[
    "惠特妮",
    "休斯顿",
    "麦当娜",
    "迈克尔",
    "杰克逊",
    "吃豆人",
    "大蜜蜂",
    "任天堂",
    "雅达利",
    "康懋达",
    "随身听",
    "披头士",
    "猫王",
    "邦乔维",
    "星球大战",
    "壮志凌云",
    "回到未来",
    "捉鬼敢死队",
    "变形金刚",
    "霹雳游侠",
    "俄罗斯方块",
    "超级马里奥",
    "马里奥",
    "大金刚",
    "太空侵略者",
    "小精灵",
    "辛迪",
    "劳帕",
    "蕾哈娜",
    "王子乐队",
    "街头霸王",
    "魂斗罗",
    "坦克大战",
    "索尼",
    "卡西欧",
    "宝丽来",
];
