[package]
name = "world-library"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
base64 = "0.23"
flate2 = "1"
world-document = { path = "../world-document" }
world-host = { path = "../world-host" }
world-pack-protocol = { path = "../world-pack-protocol" }
serde_json = "1"
world-persistence = { path = "../world-persistence" }
world-projection = { path = "../world-projection" }

[dev-dependencies]
world-builtins = { path = "../world-builtins" }
