from pathlib import Path

p = Path("worlds/pocket-universe/src/lib.rs")
text = p.read_text()
anchor = '''fn validate_mind_profile(profile: String) -> Result<String, Box<dyn Error>> {'''
helpers = '''fn with_causes(\n    mut request: ActionRequest,\n    causes: impl IntoIterator<Item = EventId>,\n) -> ActionRequest {\n    for cause in causes {\n        if !request.caused_by.contains(&cause) {\n            request.caused_by.push(cause);\n        }\n    }\n    request\n}\n\nfn latest_event_id(world: &World, kind: &str) -> Option<EventId> {\n    world\n        .events()\n        .iter()\n        .rev()\n        .find(|event| event.kind == kind)\n        .map(|event| event.id)\n}\n\nfn latest_event_id_from(world: &World, kinds: &[&str]) -> Option<EventId> {\n    world\n        .events()\n        .iter()\n        .rev()\n        .find(|event| kinds.contains(&event.kind.as_str()))\n        .map(|event| event.id)\n}\n\nfn growth_context_causes(world: &World) -> Vec<EventId> {\n    let mut causes = Vec::new();\n    for cause in [\n        latest_event_id(world, \"universe_intervened\"),\n        latest_event_id_from(world, &[\"partnership_formed\", \"relationship_fractured\"]),\n        latest_event_id(world, \"world_posture_chosen\"),\n        latest_event_id(world, \"world_legacy_formed\"),\n    ]\n    .into_iter()\n    .flatten()\n    {\n        if !causes.contains(&cause) {\n            causes.push(cause);\n        }\n    }\n    causes\n}\n\nfn growth_request(world: &World) -> ActionRequest {\n    with_causes(\n        ActionRequest::new(\"grow_universe\").actor(UNIVERSE),\n        growth_context_causes(world),\n    )\n}\n\nfn agent_turn_causes(world: &World, actor: EntityId, immediate: EventId) -> Vec<EventId> {\n    let mut causes = vec![immediate];\n    if let Some(posture) = latest_event_id(world, \"world_posture_chosen\") {\n        if !causes.contains(&posture) {\n            causes.push(posture);\n        }\n    }\n    if actor == SLOT_E {\n        if let Some(direction) = latest_event_id(world, \"relationship_steered\") {\n            if !causes.contains(&direction) {\n                causes.push(direction);\n            }\n        }\n    }\n    causes\n}\n\nfn relationship_context_causes(world: &World) -> Vec<EventId> {\n    latest_event_id(world, \"relationship_steered\")\n        .into_iter()\n        .collect()\n}\n\n'''
if text.count(anchor) != 1:
    raise SystemExit(f"helper anchor count {text.count(anchor)}")
p.write_text(text.replace(anchor, helpers + anchor, 1))
