[package]
name = "world-lineage-gpui"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
world-document = { path = "../world-document" }
world-lineage = { path = "../world-lineage" }
gpui = { git = "https://github.com/zed-industries/zed", rev = "4e8057d74db3570b3bd419ff296eb84c35b3a5a3", package = "gpui" }
