//! Each place's own ladder of works: what its people want built, one
//! after another, in its own order and at its own pace. Ares builds for
//! the dust and the supply windows, heavy work that comes slowly; Maple
//! Street builds for its kids, its radio and its nights out, quickly and
//! often; Icebridge builds for the ice, the chicks and the long night.

use crate::places::Place;
use crate::{SLOT_B, SLOT_E};
use world_core::EntityId;
use world_projection::MarkShape;

/// A work a place builds towards after its first goals: who wants it, and
/// what they say of it as it is asked for and as it goes on.
pub(crate) struct Work {
    pub(crate) id: &'static str,
    pub(crate) label: &'static str,
    pub(crate) shape: MarkShape,
    pub(crate) champion: EntityId,
    pub(crate) told: &'static str,
    pub(crate) line: &'static str,
    pub(crate) progress: &'static str,
}

const fn work(
    id: &'static str,
    label: &'static str,
    shape: MarkShape,
    champion: EntityId,
    told: &'static str,
    line: &'static str,
    progress: &'static str,
) -> Work {
    Work {
        id,
        label,
        shape,
        champion,
        told,
        line,
        progress,
    }
}

/// A place's works, in the order its people ask for them.
pub(crate) fn works(place: Place) -> &'static [Work] {
    match place {
        Place::Ares => ARES,
        Place::Maple => MAPLE,
        Place::Ice => ICE,
    }
}

/// How many periods a work rests between askings in each place: Ares's
/// heavy works come slowly, Maple Street's quickly.
pub(crate) fn rests(place: Place) -> u64 {
    match place {
        Place::Ares => 25,
        Place::Maple => 20,
        Place::Ice => 23,
    }
}

/// What each place's people say as they get on with a work themselves,
/// when the player leaves it to them or lets it go by.
pub(crate) fn on_their_own(place: Place) -> [&'static str; 4] {
    match place {
        Place::Ares => [
            "Fine. I'll do it on my off-shift.",
            "Slow going, on my own. But going.",
            "We'll get there. One bolt a sol.",
            "Nobody else was free, so I made a start.",
        ],
        Place::Maple => [
            "Guess it's me and a toolbox, then.",
            "We'll do it Saturdays. It'll get done.",
            "Slow and steady. Like the night bus.",
            "Nobody came, so I started anyway.",
        ],
        Place::Ice => [
            "Then I'll do it a flipperful at a time.",
            "Slow work, but the ice isn't going anywhere.",
            "A block a day. That's how bridges get built.",
            "Nobody came, so I started on my own.",
        ],
    }
}

const K: EntityId = SLOT_B;
const E: EntityId = SLOT_E;
const ARES: &[Work] = &[
    work(
        "ares_dust_wall",
        "A dust wall round the landing pad",
        MarkShape::Bench,
        E,
        "{explorer} wants a wall to keep the dust off the landing pad",
        "Every storm buries the pad. A wall would save us digging.",
        "Another course of sandbags on the wall.",
    ),
    work(
        "ares_water_still",
        "A water still for the ice mine",
        MarkShape::Well,
        K,
        "{keeper} wants a still to melt the ice they mine",
        "Ice in, water out. Simple, if we build it right.",
        "The still dripped its first cup today.",
    ),
    work(
        "ares_mess_hall",
        "A mess hall",
        MarkShape::Dome,
        K,
        "{keeper} wants a hall where the whole crew can eat together",
        "Somewhere we can all sit down at once.",
        "The mess hall has a roof now. Half a roof.",
    ),
    work(
        "ares_rover_shed",
        "A shed for Kestrel",
        MarkShape::Shop,
        E,
        "{explorer} wants a shed to keep Kestrel out of the storms",
        "Kestrel deserves better than a tarp.",
        "Kestrel's shed has walls. Kestrel is thrilled.",
    ),
    work(
        "ares_relay_hut",
        "A hut at the relay mast",
        MarkShape::Tent,
        E,
        "{explorer} wants a hut out at the relay mast",
        "If a storm catches me out there, I want a roof.",
        "The hut's up. It rattles, but it's up.",
    ),
    work(
        "ares_seed_vault",
        "A seed vault under the rock",
        MarkShape::Shop,
        K,
        "{keeper} wants a vault to keep the seed stock safe",
        "One bad seal and we lose every seed from Earth.",
        "The vault door fits. Tight as a drum.",
    ),
    work(
        "ares_storm_shelter",
        "A storm shelter",
        MarkShape::Dome,
        K,
        "{keeper} wants a shelter for the worst of the dust season",
        "When the big storms come, we need somewhere deep.",
        "Dug another metre into the rock.",
    ),
    work(
        "ares_solar_field",
        "A field of solar panels",
        MarkShape::Signpost,
        E,
        "{explorer} wants a field of panels out past the ridge",
        "More sun, more power, fewer cold nights.",
        "Twelve panels up and angled at the sun.",
    ),
    work(
        "ares_greenhouse_annexe",
        "A greenhouse annexe",
        MarkShape::Garden,
        K,
        "{keeper} wants a second room for the greenhouse",
        "The wheat's crowding the tomatoes. They need their own room.",
        "The annexe frame is up. The tomatoes are watching.",
    ),
    work(
        "ares_track_beacons",
        "Beacons along the rover track",
        MarkShape::Lamp,
        E,
        "{explorer} wants beacons along the rover track",
        "In a dust storm you can't see the track. Beacons would guide us home.",
        "Another beacon blinking on the track.",
    ),
    work(
        "ares_clinic",
        "A clinic bay",
        MarkShape::Tent,
        K,
        "{keeper} wants a proper clinic bay",
        "We patch each other up on the mess table. We can do better.",
        "The clinic has a bed and a light. And plasters.",
    ),
    work(
        "ares_machine_shop",
        "A machine workshop",
        MarkShape::Shop,
        K,
        "{keeper} wants a workshop to machine spare parts",
        "Every broken part waits two windows for a new one. Let's make our own.",
        "The lathe is bolted down. It hums.",
    ),
    work(
        "ares_landing_pad",
        "A proper landing pad",
        MarkShape::Flag,
        E,
        "{explorer} wants a proper pad for the shuttle to land on",
        "The shuttle lands in the dirt. One day it'll tip over.",
        "Poured another slab of the pad.",
    ),
    work(
        "ares_observatory",
        "An observatory dome",
        MarkShape::Dome,
        E,
        "{explorer} wants a dome for the telescope",
        "Earth's up there somewhere. I want to see it properly.",
        "The observatory dome turns now. Squeaks, but turns.",
    ),
    work(
        "ares_second_tank",
        "A second water tank",
        MarkShape::Well,
        K,
        "{keeper} wants a second tank for the dry months",
        "One tank is one leak away from trouble.",
        "The second tank holds. I checked it three times.",
    ),
    work(
        "ares_dust_lock",
        "A dust lock at the airlock",
        MarkShape::Shop,
        K,
        "{keeper} wants a lock to brush the dust off before coming in",
        "Dust in the filters, dust in the bunks, dust in the soup.",
        "The brushes spin. Mostly the dust goes.",
    ),
    work(
        "ares_school_pod",
        "A school pod for the cadets",
        MarkShape::Tent,
        K,
        "{keeper} wants a pod to teach the cadets in",
        "The cadets learn on their bunks. They should have a room.",
        "The school pod has a screen and six stools.",
    ),
    work(
        "ares_ice_cable",
        "A cable run to the ice mine",
        MarkShape::Signpost,
        E,
        "{explorer} wants a cable to haul ice from the mine",
        "Hauling ice by hand is breaking backs.",
        "The cable runs halfway to the mine.",
    ),
    work(
        "ares_rec_room",
        "A rec room",
        MarkShape::Dome,
        E,
        "{explorer} wants a room for music and cards",
        "We work, we sleep. We should also play.",
        "The rec room has a table and a guitar.",
    ),
    work(
        "ares_radio_tower",
        "A tall radio tower",
        MarkShape::Tower,
        E,
        "{explorer} wants a tower to talk to the Tharsis outpost",
        "Tharsis is out there. Let's say hello.",
        "The tower's another section taller.",
    ),
    work(
        "ares_landing_stone",
        "A stone for the first landing",
        MarkShape::Statue,
        K,
        "{keeper} wants a stone to mark where the first pod came down",
        "So nobody forgets where we started.",
        "The words are carved. Half of them.",
    ),
    work(
        "ares_algae_farm",
        "An algae farm",
        MarkShape::Garden,
        K,
        "{keeper} wants tanks for growing algae",
        "It tastes of nothing and feeds everyone.",
        "Two tanks bubbling green.",
    ),
    work(
        "ares_bunkhouse",
        "A bunkhouse for the new crew",
        MarkShape::House,
        K,
        "{keeper} wants a bunkhouse for whoever comes on the shuttle",
        "Every window brings more people and no more beds.",
        "Four more bunks, made up.",
    ),
    work(
        "ares_rover_lift",
        "A lift in the rover shed",
        MarkShape::Shop,
        E,
        "{explorer} wants a lift to get under the rovers",
        "I'm tired of lying in the dust to fix an axle.",
        "The lift goes up. It comes down too.",
    ),
    work(
        "ares_windbreak",
        "A windbreak for the greenhouse",
        MarkShape::Bench,
        E,
        "{explorer} wants a windbreak on the greenhouse's storm side",
        "The big storms sandblast the panels.",
        "Another stretch of windbreak stands.",
    ),
    work(
        "ares_trading_post",
        "A trading post for the outposts",
        MarkShape::Stall,
        E,
        "{explorer} wants a post to trade with the other outposts",
        "Tharsis has spare pipe. We have spare wheat.",
        "The trading post has a counter and a sign.",
    ),
    work(
        "ares_quiet_room",
        "A quiet room",
        MarkShape::Tent,
        K,
        "{keeper} wants a room for quiet",
        "Somewhere nobody talks shop. Just quiet.",
        "The quiet room has a rug. Shh.",
    ),
    work(
        "ares_book_shelves",
        "A library of Earth books",
        MarkShape::Shop,
        K,
        "{keeper} wants shelves for the books the shuttles bring",
        "Every window brings books. They're piled in the airlock.",
        "Another shelf filled.",
    ),
    work(
        "ares_mine_shaft",
        "A second shaft at the ice mine",
        MarkShape::Well,
        E,
        "{explorer} wants a second shaft at the ice mine",
        "The first shaft is running dry.",
        "The drill's thirty metres down.",
    ),
    work(
        "ares_dome_walkway",
        "A walkway between the domes",
        MarkShape::Bridge,
        K,
        "{keeper} wants a sealed walkway between the domes",
        "No more suiting up to cross the yard.",
        "The walkway's sealed at one end.",
    ),
    work(
        "ares_flower_dome",
        "A garden under the big dome",
        MarkShape::Garden,
        K,
        "{keeper} wants a garden everyone can walk in",
        "Not wheat. Flowers. Just to look at.",
        "The first flowerbed's dug.",
    ),
    work(
        "ares_welcome_arch",
        "An arch where the shuttle lands",
        MarkShape::Statue,
        E,
        "{explorer} wants an arch to welcome people off the shuttle",
        "The first thing they should see is a welcome.",
        "The arch's two legs are up. The top's next.",
    ),
];

const MAPLE: &[Work] = &[
    work(
        "maple_bus_shelter",
        "A shelter at the bus stop",
        MarkShape::Tent,
        E,
        "{explorer} wants a shelter at the Night Bus 6 stop",
        "Waiting for the night bus in the rain is the worst.",
        "The shelter's got a roof. And graffiti already.",
    ),
    work(
        "maple_snack_bar",
        "A snack bar in the arcade",
        MarkShape::Shop,
        K,
        "{keeper} wants a snack bar in the arcade",
        "Quarters in the machines, nachos in the hand.",
        "The snack bar's counter is in. The nacho machine's on order.",
    ),
    work(
        "maple_call_in_booth",
        "A booth for call-ins at K-88",
        MarkShape::Tower,
        E,
        "{explorer} wants a booth so people can call in to K-88",
        "People want to talk on the radio. Let them.",
        "The booth has a phone and a stool.",
    ),
    work(
        "maple_crosswalk",
        "A crosswalk by the school",
        MarkShape::Signpost,
        K,
        "{keeper} wants a crosswalk by the school",
        "The kids dodge traffic every morning.",
        "Painted the first white stripes.",
    ),
    work(
        "maple_bleachers",
        "Bleachers at the ballfield",
        MarkShape::Bench,
        E,
        "{explorer} wants bleachers for the Little League games",
        "Parents stand for nine innings. That's cruel.",
        "Three rows of bleachers bolted down.",
    ),
    work(
        "maple_underpass_mural",
        "A mural on the underpass",
        MarkShape::Statue,
        K,
        "{keeper} wants a mural on the ugly underpass",
        "Grey concrete. Let's give it colour.",
        "The mural has a sky now. Blue as anything.",
    ),
    work(
        "maple_splash_pool",
        "A splash pool at the park",
        MarkShape::Fountain,
        E,
        "{explorer} wants a splash pool for the summer",
        "Summer on Maple Street is ninety degrees and no shade.",
        "The pool's dug. Needs water. And tiles.",
    ),
    work(
        "maple_skate_floor",
        "A roller floor in the empty lot",
        MarkShape::Bench,
        E,
        "{explorer} wants a skating floor in the empty lot",
        "The Rialto's rink costs two bucks. Ours could be free.",
        "Half the floor's poured and smooth.",
    ),
    work(
        "maple_darkroom",
        "A darkroom at the high school",
        MarkShape::Shop,
        K,
        "{keeper} wants a darkroom for the photography club",
        "The club develops photos in a closet. With the light on, sometimes.",
        "The darkroom has its red light.",
    ),
    work(
        "maple_clubhouse",
        "A clubhouse for the kids",
        MarkShape::House,
        K,
        "{keeper} wants a clubhouse where the kids can hang out",
        "Better here than behind the gas station.",
        "The clubhouse has four walls and a sign: No Adults.",
    ),
    work(
        "maple_tall_antenna",
        "A taller antenna for K-88",
        MarkShape::Tower,
        E,
        "{explorer} wants a taller antenna so K-88 reaches the next town",
        "Right now K-88 stops at the gas station.",
        "The antenna's ten feet taller.",
    ),
    work(
        "maple_garden_plots",
        "Garden plots behind the diner",
        MarkShape::Garden,
        K,
        "{keeper} wants garden plots for anyone who wants one",
        "Grow your own tomatoes. Beat the diner's prices.",
        "Six plots dug and labelled.",
    ),
    work(
        "maple_park_stage",
        "A stage in the park",
        MarkShape::Stall,
        E,
        "{explorer} wants a stage in the park for the bands",
        "Every band on the street plays in a garage. Let them play outside.",
        "The stage has boards and a plug.",
    ),
    work(
        "maple_streetlights",
        "New streetlights on the dark end",
        MarkShape::Lamp,
        K,
        "{keeper} wants new streetlights on the dark end of the street",
        "Half the street goes dark after nine.",
        "Two more lights on the dark end.",
    ),
    work(
        "maple_tape_shelf",
        "A shelf of tapes to rent",
        MarkShape::Shop,
        K,
        "{keeper} wants a shelf of tapes to rent at the arcade",
        "Everyone wants to watch movies at home now.",
        "Forty tapes on the shelf. Rewound, mostly.",
    ),
    work(
        "maple_bike_rack",
        "A bike rack outside the school",
        MarkShape::Signpost,
        E,
        "{explorer} wants a bike rack outside the school",
        "Bikes chained to the flagpole. That's not right.",
        "The rack holds twelve bikes.",
    ),
    work(
        "maple_dance_floor",
        "A dance floor in the church hall",
        MarkShape::Bench,
        K,
        "{keeper} wants a proper floor for the school dances",
        "The gym smells like socks. Dances deserve better.",
        "The floor's sanded and shining.",
    ),
    work(
        "maple_record_library",
        "A record library at K-88",
        MarkShape::Shop,
        E,
        "{explorer} wants a record library at K-88",
        "Our records are in boxes in a closet. It's a crime.",
        "Two shelves of records, in order.",
    ),
    work(
        "maple_treehouse",
        "A treehouse in the old oak",
        MarkShape::House,
        E,
        "{explorer} wants a treehouse in the old oak",
        "Every kid deserves a treehouse. Every grown-up too.",
        "The treehouse has a floor. The ladder's next.",
    ),
    work(
        "maple_court",
        "A basketball court in the lot",
        MarkShape::Signpost,
        E,
        "{explorer} wants a court with real hoops",
        "The kids shoot at a milk crate on a pole.",
        "One hoop up. One to go.",
    ),
    work(
        "maple_pay_phone",
        "A pay phone on the corner",
        MarkShape::Postbox,
        K,
        "{keeper} wants a pay phone on the corner",
        "The nearest phone is six blocks away.",
        "The phone's in. Dial tone and everything.",
    ),
    work(
        "maple_drive_in_screen",
        "A new screen at the drive-in",
        MarkShape::Tower,
        E,
        "{explorer} wants a new screen at the drive-in",
        "The old screen has a hole right where the heroes stand.",
        "The new screen's half stretched.",
    ),
    work(
        "maple_study_room",
        "A study room at the library",
        MarkShape::Shop,
        K,
        "{keeper} wants a quiet room for studying at the library",
        "Try studying for finals with the TV on.",
        "The study room has desks and a sign that says Shh.",
    ),
    work(
        "maple_median_beds",
        "Flower beds down the median",
        MarkShape::Planter,
        K,
        "{keeper} wants flower beds down the middle of the street",
        "Something to look at besides traffic.",
        "Tulips in the first three beds.",
    ),
    work(
        "maple_soapbox_track",
        "A soapbox derby track",
        MarkShape::Bridge,
        E,
        "{explorer} wants a soapbox track down Hill Street",
        "Every kid on the street has a cart and nowhere to race it.",
        "The track's marked out with hay bales.",
    ),
    work(
        "maple_neon_sign",
        "A neon sign for the arcade",
        MarkShape::Lamp,
        K,
        "{keeper} wants a neon sign for the arcade",
        "Nobody can find us after dark.",
        "Half the letters glow. The A is stubborn.",
    ),
    work(
        "maple_diner_board",
        "A notice board at the diner",
        MarkShape::Signpost,
        K,
        "{keeper} wants a board for notices at the diner",
        "Lost dogs, lawn mowers for sale, babysitters wanted.",
        "The board's up and already full.",
    ),
    work(
        "maple_radio_van",
        "A van for K-88 to broadcast live",
        MarkShape::Rover,
        E,
        "{explorer} wants a van so K-88 can broadcast live",
        "Imagine the Bike Race on the radio, live!",
        "The van has a dish on the roof.",
    ),
    work(
        "maple_youth_centre",
        "A youth centre",
        MarkShape::House,
        K,
        "{keeper} wants a youth centre for the kids after school",
        "School's out at three and the kids have nowhere to be.",
        "The youth centre has a ping-pong table.",
    ),
    work(
        "maple_picnic_tables",
        "Picnic tables in the park",
        MarkShape::Bench,
        E,
        "{explorer} wants picnic tables in the park",
        "Picnics on a blanket are for ants.",
        "Four tables, painted green.",
    ),
    work(
        "maple_winter_rink",
        "A winter ice rink in the lot",
        MarkShape::Pier,
        E,
        "{explorer} wants to flood the lot for skating in winter",
        "Freeze the lot and we've got a rink.",
        "The boards are up round the rink.",
    ),
    work(
        "maple_square_fountain",
        "A drinking fountain on the square",
        MarkShape::Fountain,
        K,
        "{keeper} wants a drinking fountain on the square",
        "Summer's hot and the diner charges for water.",
        "The fountain works. Cold as anything.",
    ),
    work(
        "maple_party_speakers",
        "Speakers for the block parties",
        MarkShape::Tower,
        E,
        "{explorer} wants speakers for the block parties",
        "One boombox can't carry a whole street.",
        "Two speakers up on poles.",
    ),
    work(
        "maple_computer_room",
        "A computer room at the high school",
        MarkShape::Shop,
        K,
        "{keeper} wants a room of computers at the high school",
        "Computers are the future. Everyone says so.",
        "Three computers plugged in. One works.",
    ),
    work(
        "maple_walk_of_fame",
        "A walk of fame on the sidewalk",
        MarkShape::Statue,
        E,
        "{explorer} wants stars on the sidewalk for Maple Street's own",
        "Everyone on this street is somebody.",
        "Five stars set in the sidewalk.",
    ),
    work(
        "maple_school_greenhouse",
        "A greenhouse at the school",
        MarkShape::Garden,
        K,
        "{keeper} wants a greenhouse for the biology class",
        "Biology from a textbook is no biology at all.",
        "The greenhouse has glass on three sides.",
    ),
    work(
        "maple_bus_depot",
        "A bigger bus depot",
        MarkShape::House,
        E,
        "{explorer} wants a bigger depot for Night Bus 6",
        "One bus, and it sleeps in the rain.",
        "The depot has a roof big enough for two buses.",
    ),
    work(
        "maple_time_capsule",
        "A time capsule by the school",
        MarkShape::Statue,
        K,
        "{keeper} wants a time capsule buried by the school",
        "Letters to whoever lives here in 2020.",
        "The capsule's full of letters and a Rubik's cube.",
    ),
    work(
        "maple_dog_run",
        "A dog run in the park",
        MarkShape::Bench,
        E,
        "{explorer} wants a fenced run for the street's dogs",
        "The dogs need somewhere to run that isn't Mrs Henderson's lawn.",
        "The fence goes all the way round.",
    ),
    work(
        "maple_marquee",
        "A marquee for the Rialto",
        MarkShape::Lamp,
        K,
        "{keeper} wants a marquee with lights for the Rialto",
        "A movie house should look like one.",
        "Half the bulbs lit on the marquee.",
    ),
    work(
        "maple_lake_path",
        "A bike path to the lake",
        MarkShape::Bridge,
        E,
        "{explorer} wants a bike path out to the lake",
        "The road to the lake is all trucks.",
        "Another quarter-mile of path.",
    ),
    work(
        "maple_gazebo",
        "A gazebo on the square",
        MarkShape::Tent,
        K,
        "{keeper} wants a gazebo on the square",
        "Somewhere to sit when it rains.",
        "The gazebo has its roof.",
    ),
    work(
        "maple_studio",
        "A recording studio at K-88",
        MarkShape::Shop,
        E,
        "{explorer} wants a studio so local bands can record",
        "Every band on the street deserves a demo tape.",
        "The egg boxes are on the walls. Soundproof, sort of.",
    ),
    work(
        "maple_market_stalls",
        "Stalls for a Saturday market",
        MarkShape::Stall,
        K,
        "{keeper} wants stalls for a Saturday market",
        "Fresh corn from the farms, right here on the street.",
        "Six stalls up in a row.",
    ),
    work(
        "maple_bank_clock",
        "A working clock on the old bank",
        MarkShape::Tower,
        K,
        "{keeper} wants the clock on the old bank working again",
        "It's said twenty past four since 1971.",
        "The hands move. Wrong time, but they move.",
    ),
    work(
        "maple_skate_park",
        "A skate park by the lake",
        MarkShape::Bench,
        E,
        "{explorer} wants a skate park out by the lake",
        "The kids skate the bank steps. The bank is not happy.",
        "Two ramps and a half-pipe.",
    ),
    work(
        "maple_henderson_bench",
        "A bench for Mrs Henderson",
        MarkShape::Bench,
        K,
        "{keeper} wants a bench in memory of Mrs Henderson",
        "She sat on her porch every evening. She'd like a bench.",
        "The bench has her name on it.",
    ),
    work(
        "maple_arcade_upstairs",
        "A second floor for the arcade",
        MarkShape::House,
        K,
        "{keeper} wants a second floor for the arcade",
        "Sixty machines, forty spaces.",
        "The stairs go up to nothing yet.",
    ),
    work(
        "maple_welcome_sign",
        "A Welcome to Maple Street sign",
        MarkShape::Signpost,
        E,
        "{explorer} wants a sign where the street begins",
        "People should know they've arrived somewhere.",
        "The sign's painted. The W is a bit wobbly.",
    ),
    work(
        "maple_transmitter",
        "A second transmitter for K-88",
        MarkShape::Tower,
        E,
        "{explorer} wants a second transmitter so K-88 reaches the city",
        "The city should hear what Maple Street sounds like.",
        "The second transmitter's wired in.",
    ),
];

const ICE: &[Work] = &[
    work(
        "ice_snow_wall",
        "A snow wall round the nests",
        MarkShape::Bench,
        K,
        "{keeper} wants a wall of snow round the nests",
        "The wind finds every egg. Let's stop it.",
        "Another row of snow blocks on the wall.",
    ),
    work(
        "ice_bridge_hole",
        "A fishing hole by the bridge",
        MarkShape::Well,
        E,
        "{explorer} wants a new fishing hole near the bridge",
        "The far hole's a long waddle with a fish in your beak.",
        "The ice is chipped half through.",
    ),
    work(
        "ice_ice_house",
        "An ice house for the vault",
        MarkShape::Shop,
        E,
        "{explorer} wants an ice house to keep the fish fresh",
        "Fish go off when the thaw comes. An ice house would keep them.",
        "The ice house has walls. Cold ones.",
    ),
    work(
        "ice_creche",
        "A crèche for the chicks",
        MarkShape::Tent,
        K,
        "{keeper} wants a crèche where the chicks can huddle",
        "The chicks wander. A crèche would keep them warm and in one place.",
        "The crèche's floor is packed smooth.",
    ),
    work(
        "ice_bridge_lanterns",
        "Lanterns along the bridge",
        MarkShape::Lamp,
        K,
        "{keeper} wants lanterns all along the bridge",
        "In the long night nobody should cross in the dark.",
        "Another lantern lit on the bridge.",
    ),
    work(
        "ice_berg_lookout",
        "A lookout on the tall berg",
        MarkShape::Tower,
        E,
        "{explorer} wants a lookout on the tall berg",
        "I want to see the seals before they see us.",
        "Steps cut halfway up the berg.",
    ),
    work(
        "ice_sea_slide",
        "A proper slide to the sea",
        MarkShape::Bridge,
        E,
        "{explorer} wants a slide straight down to the water",
        "Waddling down to the sea is slow. Sliding is fast.",
        "The slide's smooth to the halfway mark.",
    ),
    work(
        "ice_council_ring",
        "A ring of stones for the council",
        MarkShape::Statue,
        K,
        "{keeper} wants a ring of stones for the council to stand in",
        "The council meets in a muddle. It should meet in a ring.",
        "Six stones stand in the ring.",
    ),
    work(
        "ice_kelp_beds",
        "Kelp beds in the shallows",
        MarkShape::Garden,
        E,
        "{explorer} wants kelp beds tended in the shallows",
        "Kelp for the lean months, if we plant it now.",
        "The first beds are pegged down.",
    ),
    work(
        "ice_thaw_marker",
        "A thaw marker on the floe",
        MarkShape::Signpost,
        K,
        "{keeper} wants a marker to see how fast the ice is thinning",
        "Every thaw the ice goes a little further. I want to know how far.",
        "The marker's in and notched.",
    ),
    work(
        "ice_wind_shelter",
        "A shelter out of the wind",
        MarkShape::Tent,
        K,
        "{keeper} wants a shelter hollowed out of the wind",
        "In a blizzard we need somewhere to huddle that isn't open ice.",
        "The shelter's dug deep enough for six.",
    ),
    work(
        "ice_second_vault",
        "A second fish vault",
        MarkShape::Shop,
        E,
        "{explorer} wants a second vault for the big catches",
        "The vault's full by midsummer. Then what?",
        "The second vault's walls are packed.",
    ),
    work(
        "ice_rope_bridge",
        "A rope bridge to the far floe",
        MarkShape::Bridge,
        K,
        "{keeper} wants a bridge of kelp rope to the far floe",
        "When the ice parts, the far floe's cut off.",
        "The rope's across. Knotted, anyway.",
    ),
    work(
        "ice_song_stone",
        "A song stone",
        MarkShape::Statue,
        E,
        "{explorer} wants a stone where the colony can sing",
        "Our songs sound best off something that echoes.",
        "The song stone's hollowed. It hums.",
    ),
    work(
        "ice_egg_warmer",
        "A warm spot for the eggs",
        MarkShape::Well,
        K,
        "{keeper} wants a warm spot by the vents for the eggs",
        "Every egg needs warm feet. Some feet are colder than others.",
        "The warm spot's lined with feathers.",
    ),
    work(
        "ice_ridge_steps",
        "Snow steps up the ridge",
        MarkShape::Bridge,
        K,
        "{keeper} wants steps cut up the ridge",
        "The ridge is steep and the old steps slip.",
        "Twenty steps cut. Fifty to go.",
    ),
    work(
        "ice_deep_ledge",
        "A fishing ledge over the deep",
        MarkShape::Pier,
        E,
        "{explorer} wants a ledge over the deep water",
        "The best fish are where the ice ends.",
        "The ledge is frozen solid. Good.",
    ),
    work(
        "ice_story_circle",
        "A circle for storytelling",
        MarkShape::Statue,
        K,
        "{keeper} wants a circle where the old ones tell stories",
        "The chicks should hear how the colony began.",
        "The circle's marked with pebbles.",
    ),
    work(
        "ice_breathing_hole",
        "A breathing hole kept open all winter",
        MarkShape::Well,
        E,
        "{explorer} wants a breathing hole kept open all winter",
        "When the sea freezes, the fish need air and we need the fish.",
        "The hole's open, and we take turns keeping it so.",
    ),
    work(
        "ice_aurora_seat",
        "A seat for watching the aurora",
        MarkShape::Bench,
        K,
        "{keeper} wants a seat carved for the aurora nights",
        "Everyone stands with their necks cricked. Let's sit.",
        "The seat's carved. It's cold, but it's a seat.",
    ),
    work(
        "ice_nest_row",
        "A row of new nests",
        MarkShape::House,
        K,
        "{keeper} wants a row of new nests for the couples",
        "There are couples with nowhere to nest.",
        "Four new nests, pebbled.",
    ),
    work(
        "ice_kelp_racks",
        "Drying racks for kelp",
        MarkShape::Planter,
        E,
        "{explorer} wants racks to dry kelp for the winter",
        "Dried kelp keeps. Wet kelp rots.",
        "The racks are strung with kelp.",
    ),
    work(
        "ice_bridge_gate",
        "A gate on the bridge",
        MarkShape::Signpost,
        K,
        "{keeper} wants a gate on the bridge for the long night",
        "Nobody should wander off the bridge in the dark.",
        "The gate's up. It creaks.",
    ),
    work(
        "ice_seal_watch",
        "A seal watch post",
        MarkShape::Tower,
        E,
        "{explorer} wants a post to watch for leopard seals",
        "One seal took three fish and a feather last year.",
        "The post's up on the edge.",
    ),
    work(
        "ice_snow_hall",
        "A snow hall for the Great Huddle",
        MarkShape::Dome,
        K,
        "{keeper} wants a hall of snow big enough for everyone",
        "The whole colony should fit under one roof.",
        "The dome's walls meet at the top.",
    ),
    work(
        "ice_run_markers",
        "Markers for the fish runs",
        MarkShape::Signpost,
        E,
        "{explorer} wants markers where the fish run",
        "The fish come the same way every year. Mark it!",
        "Three markers bob in the water.",
    ),
    work(
        "ice_far_lantern",
        "A lantern at the far floe",
        MarkShape::Lamp,
        K,
        "{keeper} wants a lantern at the far floe",
        "The far floe's dark as a whale's belly.",
        "The far lantern burns.",
    ),
    work(
        "ice_chick_slide",
        "A little slide for the chicks",
        MarkShape::Swing,
        E,
        "{explorer} wants a little slide just for the chicks",
        "The big slide's too fast for the little ones.",
        "The chick slide is gentle and very popular.",
    ),
    work(
        "ice_bone_arch",
        "An arch of whale bones",
        MarkShape::Statue,
        K,
        "{keeper} wants an arch from the old whale bones",
        "The bones have lain there since before my grandmother. Let's make something of them.",
        "The arch stands. Mind your head.",
    ),
    work(
        "ice_salt_pans",
        "Salt pans on the rocks",
        MarkShape::Garden,
        E,
        "{explorer} wants salt pans to cure the fish",
        "Salted fish keeps all winter.",
        "The first pan's crusted white.",
    ),
    work(
        "ice_thaw_channel",
        "A channel through the thaw ice",
        MarkShape::Bridge,
        E,
        "{explorer} wants a channel cut through the thinning ice",
        "When the thaw comes, the ice traps us. A channel would free us.",
        "The channel's cut halfway to open water.",
    ),
    work(
        "ice_swim_pool",
        "A sheltered pool for swimming lessons",
        MarkShape::Fountain,
        K,
        "{keeper} wants a sheltered pool to teach the chicks to swim",
        "The open sea is too rough for first swims.",
        "The pool's walled on three sides.",
    ),
    work(
        "ice_pebble_market",
        "A pebble market",
        MarkShape::Stall,
        E,
        "{explorer} wants a place to trade pebbles and fish",
        "Everyone has something someone else wants.",
        "The market has a counter of ice.",
    ),
    work(
        "ice_night_beacon",
        "A beacon for the long night",
        MarkShape::Tower,
        K,
        "{keeper} wants a beacon to guide the fishers home in the dark",
        "In the long night the fishers get lost coming home.",
        "The beacon's oil is in. It just needs lighting.",
    ),
    work(
        "ice_elders_ramp",
        "A ramp for the old ones",
        MarkShape::Bridge,
        K,
        "{keeper} wants a gentle ramp for the old ones",
        "Grandma Olo can't manage the steps any more.",
        "The ramp's packed smooth.",
    ),
    work(
        "ice_name_wall",
        "A wall of carved names",
        MarkShape::Statue,
        E,
        "{explorer} wants a wall where everyone carves their name",
        "So the colony remembers who was here.",
        "Twelve names carved so far.",
    ),
    work(
        "ice_fog_horn",
        "A shell horn for foggy days",
        MarkShape::Signpost,
        K,
        "{keeper} wants a horn to blow on foggy days",
        "In the fog you can't see your own flipper.",
        "The horn blows. Loud!",
    ),
    work(
        "ice_new_floe_bridge",
        "A bridge to the new floe",
        MarkShape::Bridge,
        K,
        "{keeper} wants a bridge out to the new floe",
        "The colony's outgrown the old floe.",
        "The first span reaches the new floe.",
    ),
];
